(()=>{'use strict';
const root=document.getElementById('curiosity');if(!root)return;
const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
const buttons=all('button[data-focus]'),studies=all('[data-study]'),seen=new Set();
let active='connection',audio=null,playing=false,frame=0,start=0,lastTick=-1;
// These events are integration hooks only. No analytics request or personal data is sent.
const emit=(action,focus=active)=>root.dispatchEvent(new CustomEvent('cabinet-interaction',{bubbles:true,detail:{action,focus}}));
const rhythms={traditional:{offsets:[0,1,1.5],labels:['1','2','&'],notation:'1 · 2 &'},rnb:{offsets:[0,.5,1],labels:['1','&','2'],notation:'1 & 2 ·'},contemporary:{offsets:[0,.5,1.5],labels:['1','&','&'],notation:'1 & · &'}};
let rhythm='traditional';
function stop(){playing=false;cancelAnimationFrame(frame);$('#cabinetPlay').textContent='▶ Play with sound';$('#cabinetPlay').setAttribute('aria-pressed','false');all('[data-step]').forEach(e=>e.classList.remove('isBeat'));$('#rhythmPlayhead').style.left='0%';if(audio&&audio.state==='running')audio.suspend().catch(()=>{});}
function select(key,announce=false){if(!studies.some(s=>s.dataset.study===key))return;stop();active=key;seen.add(key);studies.forEach(s=>s.hidden=s.dataset.study!==key);buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.focus===key)));$('#cabinetVisited').textContent=seen.size+' of 3 curiosities opened · Follow whatever interests you.';if(announce){$('.curiosityStatus').textContent=buttons.find(b=>b.dataset.focus===key).querySelector('strong').textContent+' opened. Its experiment and learning links are below.';emit('open');studies.find(s=>s.dataset.study===key).scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}}
buttons.forEach(b=>b.addEventListener('click',()=>select(b.dataset.focus,true)));
$('.cabinetSurprise').addEventListener('click',()=>{const unseen=buttons.filter(b=>!seen.has(b.dataset.focus)),pool=unseen.length?unseen:buttons.filter(b=>b.dataset.focus!==active);select(pool[Math.floor(Math.random()*pool.length)].dataset.focus,true);});
const questions=[
 {category:'CONNECTION',title:'What do you want your partner to feel?',answer:'Pick one word: clarity, ease, playfulness… Next time you dance, let that intention guide a simple phrase. Afterwards, ask your partner what they noticed.',image:'demonstration',alt:'Gab exploring movement with a partner during a workshop'},
 {category:'MUSICALITY',title:'What if you listened for something new?',answer:'Listen to a familiar song without dancing. Follow one instrument you usually overlook. When you dance again, notice whether it offers you a different choice.',image:'workshop',alt:'Gab practicing with a group of dancers in a studio'},
 {category:'CURIOSITY',title:'What would you keep from your last dance?',answer:'Name one moment you enjoyed, however small. What made it work for you? Bring that observation to your next lesson: useful practice can begin with what is already working.',image:'movement',alt:'Gab exploring balance in a movement pose'}
];let questionIndex=0,questionOpen=false;
$('#questionReveal').addEventListener('click',()=>{if(!questionOpen){questionOpen=true;$('#questionAnswer').hidden=false;$('#questionReveal').textContent='Another question ↗';emit('question-reveal');return;}questionIndex=(questionIndex+1)%questions.length;questionOpen=false;const q=questions[questionIndex];$('#questionCategory').textContent=q.category;$('#questionTitle').textContent=q.title;$('#questionAnswer').textContent=q.answer;$('#questionAnswer').hidden=true;$('#questionImage').src='/assets/editorial/'+q.image+'.webp';$('#questionImage').alt=q.alt;$('#questionCounter').textContent='0'+(questionIndex+1)+' / 03';$('#questionReveal').textContent='Turn the question over ↗';emit('question-next');});
function note(index){if(!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type=index===2?'triangle':'sine';o.frequency.setValueAtTime([150,260,650][index],now);o.frequency.exponentialRampToValueAtTime([55,130,330][index],now+.10);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.12,now+.008);g.gain.exponentialRampToValueAtTime(.001,now+.12);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.13);o.onended=()=>{o.disconnect();g.disconnect();};}
function tick(now){if(!playing)return;const elapsed=(now-start)/1000,beat=elapsed*1.5,slot=Math.floor(beat*2),phase=(beat%2)/2;$('#rhythmPlayhead').style.left=(phase*100)+'%';if(slot!==lastTick){lastTick=slot;const index=rhythms[rhythm].offsets.findIndex(x=>x*2===slot%4);all('[data-step]').forEach((e,i)=>e.classList.toggle('isBeat',i===index));if(index>=0)note(index);}frame=requestAnimationFrame(tick);}
all('[data-rhythm]').forEach(b=>b.addEventListener('click',()=>{rhythm=b.dataset.rhythm;all('[data-rhythm]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#rhythmNotation').textContent=rhythms[rhythm].notation;all('[data-step]').forEach((e,i)=>{e.querySelector('span').textContent=rhythms[rhythm].labels[i];});start=performance.now();lastTick=-1;emit('rhythm-change');}));
$('#cabinetPlay').addEventListener('click',async()=>{if(playing){stop();return;}const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){$('#rhythmHint').textContent='Audio is unavailable in this browser. Compare the counts above, or open Zoukable.';return;}$('#cabinetPlay').disabled=true;try{audio=audio||new Audio();await audio.resume();if(active!=='musicality'||document.hidden)return;playing=true;start=performance.now();lastTick=-1;$('#cabinetPlay').textContent='■ Stop sound';$('#cabinetPlay').setAttribute('aria-pressed','true');frame=requestAnimationFrame(tick);emit('rhythm-play');}catch{$('#rhythmHint').textContent='Sound could not start. Try again, or compare the counts above.';}finally{$('#cabinetPlay').disabled=false;}});
const journey=[
 ['IN YOUR LESSON','“Why does this step feel rushed?”','You bring a real question. Together, we notice when your weight arrives and what happens just before the next step.','You leave with: one clear thing to pay attention to.'],
 ['EXPLORE WITH YOUR COACH','Change one thing. Notice the difference.','We slow the phrase down and compare two timings. You explore whether allowing the weight transfer to finish changes how the next step feels.','You leave with: an experiment, not a list of corrections.'],
 ['BETWEEN LESSONS / ZOUKABLE','Make a small practice repeatable.','Use the rhythm tools to revisit a short phrase. Change the tempo, notice what stays clear, and keep a question for your next lesson.','Your practice: a few attentive repetitions, rather than chasing XP.'],
 ['BACK WITH YOUR COACH / ATLAS','What changed—and what still needs attention?','Bring your observations back. Your coach helps you refine the idea and records the concepts you explored in Atlas. Practice activity alone never certifies a skill.','Your Atlas: coach-recorded discoveries, with more room to explore.'],
 ['CONNECT IT TO YOUR DANCING','One discovery opens another question.','Try that timing idea with another phrase or partner. Does it change your listening or connection? You might revisit an earlier step or explore a new branch.','The next question belongs to you. The map stays unfinished.']
];let journeyIndex=0;
function showJourney(n){journeyIndex=n;all('[data-journey]').forEach(x=>x.setAttribute('aria-pressed',String(Number(x.dataset.journey)===n)));all('[data-map-node]').forEach((e,i)=>e.classList.toggle('lit',i<=n));$('#cabinetMapPath').setAttribute('d',['M60 215','M60 215 L145 115','M60 215 L145 115 L260 175','M60 215 L145 115 L260 175 L350 70','M60 215 L145 115 L260 175 L350 70 L440 155'][n]);['#journeyPlace','#journeyTitle','#journeyInsight','#journeyTakeaway'].forEach((id,i)=>$(id).textContent=journey[n][i]);$('#journeyCounter').textContent='0'+(n+1)+' / 05';$('#journeyBack').disabled=n===0;$('#journeyNext').textContent=n===4?'Explore again ↺':'Next discovery →';emit('journey-explore');}
all('[data-journey]').forEach(b=>b.addEventListener('click',()=>showJourney(Number(b.dataset.journey))));$('#journeyBack').addEventListener('click',()=>showJourney(Math.max(0,journeyIndex-1)));$('#journeyNext').addEventListener('click',()=>showJourney((journeyIndex+1)%5));
all('[data-cabinet-cta]').forEach(a=>a.addEventListener('click',()=>emit('learning-link',a.dataset.cabinetCta)));
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
if('IntersectionObserver'in window)new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stop();},{threshold:0}).observe(root);
select('connection');$('[data-map-node="0"]').classList.add('lit');$('.curiosityChoices').hidden=false;$('.cabinetSurprise').hidden=false;all('.experimentControls').forEach(e=>e.hidden=false);
})();
