(() => {
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let client,coach=false,epoch=0,rows=[],offset=0,storyOffset=0,pending=null,busy=false;
const value=id=>$(id).value.trim();
function preview(){const allowed=$('website_consent').checked||$('ads_consent').checked;const custom=$('creditMode').value==='custom';$('creditField').hidden=!custom;$('credit').required=allowed&&custom;$('quote').required=allowed;$('quote').minLength=allowed?10:0;$('email').required=$('follow_up').checked;$('quotePreview').hidden=!allowed;$('quotePreview').textContent=allowed?'Sharing preview: “'+value('quote')+'” — '+(custom?value('credit'):'Anonymous student'):'';}
$('feedbackForm').addEventListener('input',preview);
$('feedbackForm').addEventListener('submit',async e=>{e.preventDefault();if(!client||busy||!$('feedbackForm').reportValidity())return;if(value('website'))return;
 const data={experience:value('experience'),rating:Number(value('rating'))||null,helpful:value('helpful'),improve:value('improve'),goals:value('goals'),name:value('name'),email:value('email'),follow_up:$('follow_up').checked,quote:value('quote'),credit:$('creditMode').value==='anonymous'?'Anonymous student':value('credit'),website_consent:$('website_consent').checked,ads_consent:$('ads_consent').checked};
 const serialized=JSON.stringify(data);if(!pending||pending.serialized!==serialized)pending={serialized,id:crypto.randomUUID()};busy=true;$('submitFeedback').disabled=true;$('formStatus').textContent='Sending your feedback…';
 try{const r=await client.from('student_feedback').insert({id:pending.id,...data});if(r.error&&r.error.code!=='23505')throw Error();$('receipt').textContent='Your reference: '+pending.id+'. Save this if you want to change your sharing permissions or request removal.';$('feedbackForm').hidden=true;$('success').hidden=false;$('success').focus();if(coach)inbox(true);}catch(_){$('formStatus').textContent='We could not confirm your submission. Your answers are still here. Please retry; retrying unchanged answers will not create a duplicate.';}finally{busy=false;$('submitFeedback').disabled=false;}
});
async function stories(reset=true){if(reset){storyOffset=0;$('stories').replaceChildren();}try{const r=await client.from('student_testimonials').select('quote,credit,experience,published_at').order('published_at',{ascending:false}).order('id').range(storyOffset,storyOffset+9);if(r.error)throw Error();$('stories').insertAdjacentHTML('beforeend',r.data.map(x=>'<article><blockquote>“'+esc(x.quote)+'”</blockquote><p>— '+esc(x.credit)+' · '+esc(x.experience)+'</p></article>').join(''));if(!storyOffset&&!r.data.length)$('stories').textContent='Stories will appear here after permission and coach review.';storyOffset+=r.data.length;$('moreStories').hidden=r.data.length<10;}catch(_){$('stories').textContent='Student stories are temporarily unavailable.';}}
async function inbox(reset=true){if(!coach)return;const run=epoch;if(reset){offset=0;rows=[];}$('inboxStatus').textContent='Loading responses…';try{let q=client.from('student_feedback').select('*').order('created_at',{ascending:false}).order('id');const filter=$('reviewFilter').value;if(filter==='reply')q=q.eq('follow_up',true);if(filter==='website')q=q.eq('website_consent',true);if(filter==='ads')q=q.eq('ads_consent',true);const r=await q.range(offset,offset+19);if(run!==epoch||!coach)return;if(r.error)throw Error();rows.push(...r.data);offset+=r.data.length;$('moreResponses').hidden=r.data.length<20;
 $('responses').innerHTML=rows.map(x=>`<article><h3>${esc(x.experience)} · ${x.rating?esc(x.rating)+'/5':'Not rated'}</h3><p>${esc(x.name||'No name supplied')} · ${esc(new Date(x.created_at).toLocaleDateString())}</p><p><strong>Helpful:</strong> ${esc(x.helpful||'—')}</p><p><strong>Improve:</strong> ${esc(x.improve)}</p><p><strong>Next goals:</strong> ${esc(x.goals||'—')}</p><p><strong>Contact:</strong> ${esc(x.email||'Not supplied')} · ${x.follow_up?'Reply requested':'No reply requested'}</p><hr><p><strong>Separate testimonial:</strong> ${esc(x.quote||'Not supplied')}</p><p>Credit: ${esc(x.credit||'—')}<br>Website: ${x.website_consent?'PERMITTED':'NOT PERMITTED'} · Advertising: ${x.ads_consent?'PERMITTED':'NOT PERMITTED'}<br>Permission record: ${esc(x.consent_version)} · ${esc(x.created_at)}</p>${x.website_consent?`<button type="button" data-action="publish" data-id="${x.id}">Publish this testimonial</button>`:''}<button type="button" data-action="unpublish" data-id="${x.id}">Remove from website</button>${x.ads_consent?`<button type="button" data-action="copy" data-id="${x.id}">Copy advertising-authorized quote</button>`:''}<button type="button" data-action="delete" data-id="${x.id}">Delete response &amp; testimonial</button><p class="small">Reference: ${esc(x.id)}</p></article>`).join('');$('inboxStatus').textContent=rows.length?rows.length+' responses loaded. Publishing shares only the exact testimonial and chosen credit.':'No responses yet.';}catch(_){if(run===epoch)$('inboxStatus').textContent='Could not load responses. Try Refresh.';}}
$('responses').addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b||!coach)return;const x=rows.find(x=>x.id===b.dataset.id);if(!x)return;const a=b.dataset.action;
 if(a==='copy'){if(!x.ads_consent)return;try{await navigator.clipboard.writeText('“'+x.quote+'” — '+x.credit);$('inboxStatus').textContent='Advertising-authorized testimonial copied. Keep its wording and credit unchanged.';}catch(_){$('inboxStatus').textContent='Copy unavailable. Select the separate testimonial text manually.';}return;}
 if(!confirm(a==='publish'?'Publish this exact testimonial and credit publicly?':a==='delete'?'Permanently delete this response and its public testimonial? Also remove promotional copies you control.':'Remove this testimonial from the website?'))return;
 b.disabled=true;try{const r=a==='publish'?await client.from('student_testimonials').insert({id:x.id}):await client.from(a==='delete'?'student_feedback':'student_testimonials').delete().eq('id',x.id);if(r.error&&!(a==='publish'&&r.error.code==='23505'))throw Error();if(!coach)return;await inbox(true);await stories();$('inboxStatus').textContent=a==='publish'?'Testimonial published.':a==='delete'?'Response and public testimonial deleted.':'Testimonial removed from website.';}catch(_){$('inboxStatus').textContent='That action could not be completed. Refresh and retry.';}finally{b.disabled=false;}
});
$('refreshInbox').onclick=()=>inbox(true);$('reviewFilter').onchange=()=>{epoch++;inbox(true);};$('moreResponses').onclick=()=>inbox(false);$('moreStories').onclick=()=>stories(false);
function clearCoach(){epoch++;coach=false;rows=[];offset=0;$('responses').replaceChildren();$('inboxStatus').textContent='';$('feedbackInbox').hidden=true;}
async function identity(){clearCoach();const run=epoch;const u=await client.auth.getUser();if(run!==epoch||!u.data.user)return;const p=await client.from('profiles').select('role').eq('id',u.data.user.id).maybeSingle();if(run!==epoch)return;coach=p.data?.role==='coach';$('feedbackInbox').hidden=!coach;if(coach)inbox(true);}
(async()=>{try{client=supabase.createClient(GAB_PORTAL.supabaseUrl,GAB_PORTAL.supabaseAnonKey);$('submitFeedback').disabled=false;$('formStatus').textContent='';preview();stories();await identity();client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')clearCoach();else if(event==='SIGNED_IN')setTimeout(identity,0);});}catch(_){$('formStatus').textContent='The form connection is unavailable. Please reload or email riseadance@gmail.com.';}})();
})();
