// Public crew identity. Authorization continues to use protected profiles.role.
window.GAB_CREW = {
  titleFor(profile) {
    if (profile?.id === 'a4bd6adb-b839-4abd-bb1c-db56e1740385') return 'Mission Control · COO';
    if (!profile || profile.role !== 'coach') return 'Mentee';
    if (profile.id === '6ff7b4ad-7246-4d72-aaa0-9a0a50fbdb98') return 'Captain';
    if (profile.id === 'b88dbca6-5f55-4ebb-a3d9-baced34b80f7') return 'Co-Captain';
    return 'Coach';
  },
  saucer: `<svg class="crewSaucer" viewBox="0 0 180 120" aria-hidden="true"><defs><linearGradient id="saucerMetal" x2="0" y2="1"><stop stop-color="#fff0c8"/><stop offset="1" stop-color="#829caf"/></linearGradient></defs><path d="M64 88 44 116H136L116 88" fill="#8ad8d0" opacity=".12"/><ellipse cx="90" cy="72" rx="77" ry="22" fill="url(#saucerMetal)" stroke="#e7c78e" stroke-width="2"/><path d="M51 62C54 13 126 13 129 62Z" fill="#5caaa9" fill-opacity=".75" stroke="#b8eeee" stroke-width="2"/><path d="M65 47C70 31 86 27 95 29" fill="none" stroke="#efffff" stroke-opacity=".75" stroke-width="4" stroke-linecap="round"/><ellipse cx="90" cy="71" rx="64" ry="10" fill="#23374c"/><g fill="#efdb9a"><ellipse cx="43" cy="76" rx="5" ry="3"/><ellipse cx="66" cy="81" rx="5" ry="3"/><ellipse cx="90" cy="83" rx="5" ry="3"/><ellipse cx="114" cy="81" rx="5" ry="3"/><ellipse cx="137" cy="76" rx="5" ry="3"/></g></svg>`,
  markup: `<section class="crewSection" aria-labelledby="crewHeading"><div class="crewIntro"><p class="crewEyebrow">THE MENTORSHIP CREW</p><h2 id="crewHeading">Meet your flight crew.</h2><p>Gab and Steph guide the journey, with Lorell at Mission Control. Your discoveries give the adventure its direction.</p></div><div class="crewProfiles"><article class="crewProfile"><div class="crewIdentity"><img class="crewAvatar" src="/gab-captain-avatar.svg" width="67" height="72" alt="Gab’s crowned captain avatar" decoding="async"><span class="crewRank">01 / CAPTAIN</span></div><h3>Gab Lacarriere</h3><p class="crewRole">Captain · Curriculum &amp; mentorship</p><p>The creator of the Zouk Atlas and the draft curriculum behind your map. Explore movement, connect ideas and bring your questions into your next lesson.</p><a href="/about/">Meet Gab →</a></article><article class="crewProfile"><div class="crewIdentity"><img class="crewAvatar" src="/steph-cocaptain-avatar.svg" width="67" height="72" alt="Steph’s co-captain avatar holding a compass" decoding="async"><span class="crewRank">02 / CO-CAPTAIN</span></div><h3>Steph</h3><p class="crewRole">Co-Captain · The Zouk Life</p><p>Alongside Gab on the mentorship ship, Steph is your Co-Captain. You can also find them together through Tuesday Zouk classes and Zouk BNB.</p><a href="/zouk-bnb/">Meet your Zouk BNB hosts →</a></article><article class="crewProfile"><span class="crewRank">03 / MISSION CONTROL</span><h3>Lorell</h3><p class="crewRole">Chief Operations Officer · Mission Control</p><p>Every voyage needs Mission Control. Lorell is the operations lead on our mentorship crew, helping keep the journey coordinated as we explore together.</p><a href="/comms-deck/">Join the crew on ECHO →</a></article></div><p class="crewWelcome">A shared ship. A personal path through the stars.</p></section>`
};

// Small shared scenes; decorative characters never represent live availability.
window.GAB_CREW.adventure = function(mode = 'explore') {
  const cockpit = mode === 'cockpit';
  return `<aside class="crewAdventure ${cockpit ? 'crewCockpit' : ''}"><div class="crewMiniScene" aria-hidden="true"><span class="crewMiniStars">✦ · ✧</span><img src="/gab-captain-avatar.svg" alt="" width="56" height="60"><img src="/steph-cocaptain-avatar.svg" alt="" width="56" height="60"><span class="crewConsole">● ━ ● ━ ●</span></div><div><p class="crewEyebrow">${cockpit ? 'ABOARD THE SHIP' : 'YOUR EXPLORATION CREW'}</p><strong>${cockpit ? 'A little guidance for your voyage.' : 'Ready to explore?'}</strong><p>Gab &amp; Steph · Captain &amp; Co-Captain</p><a href="${cockpit ? '/comms-deck/' : '/zouk-map/#map'}">${cockpit ? 'Talk with your crew on ECHO' : 'Explore your Zouk Atlas'} →</a></div></aside>`;
};
