(() => {
'use strict';
const cfg=window.GAB_PORTAL,root=document.getElementById('teachingWorkbench'),bar=document.getElementById('accountBar');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let client,user=null,initializing=true;
function gate(message='') {root.innerHTML=`<section class="toolPanel accountGate"><p class="kicker">Your teaching studio</p><h2>Sign in to your website account.</h2><p>Your Zouk and Lambada plans stay together here, ready when you return on any device.</p><form id="plannerLogin"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="toolPrimary" type="submit">Sign in &amp; open my plans</button><p id="plannerLoginMessage" role="status">${esc(message)}</p></form><p><a href="/mentorship-hub/">Password help / member account</a> · <a href="/for-teachers/#teacher-contact">Ask Gab for teacher access</a></p><p class="toolHint">Use the same login as the rest of the website. Signing in here does not change your mentorship membership.</p></section>`;}
async function read(){const {data,error}=await client.from('teacher_workspaces').select('document,revision,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return data||{document:{version:2,courses:[],sessions:[]},revision:0};}
async function load(){if(!cfg||!window.supabase){root.textContent='The account service could not load. Refresh to try again.';throw Error('Account service unavailable');}client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const result=await client.auth.getUser();user=result.data?.user||null;
 if(!user){gate();await new Promise(resolve=>{root.addEventListener('submit',async event=>{if(event.target.id!=='plannerLogin')return;event.preventDefault();const form=event.target,button=form.querySelector('button'),message=document.getElementById('plannerLoginMessage');button.disabled=true;message.textContent='Signing in…';try{const values=new FormData(form);const {data,error}=await client.auth.signInWithPassword({email:String(values.get('email')).trim(),password:String(values.get('password'))});if(error)throw error;user=data.user;form.reset();resolve();}catch{message.textContent='Sign-in did not complete. Check your details or use the account-help link.';}finally{button.disabled=false;}});});}
 bar.innerHTML=`<span>Signed in as ${esc(user.email||'member')}</span><a href="/mentorship-hub/">My member space ↗</a><button id="plannerSignout" type="button">Sign out</button>`;
 document.getElementById('plannerSignout').onclick=async()=>{if(window.TeacherPlannerFlush&&!await window.TeacherPlannerFlush())return;await client.auth.signOut();location.reload();};
 client.auth.onAuthStateChange((event,session)=>{if(initializing)return;if(!session||session.user.id!==user.id){root.replaceChildren();bar.textContent='Your account changed. Reloading…';location.reload();}});
 const workspace=await read();initializing=false;return {workspace,userId:user.id};}
window.TeacherCloud={load,read,async save(document,revision){const {data,error}=await client.rpc('save_teacher_workspace',{p_document:document,p_expected_revision:revision});if(error)throw error;return data;}};
})();
