/* Original planning prompts. Source traditions inform the categories; templates are editable drafts, not official syllabi or readiness certification. */
window.DANCE_PLANNER_LIBRARY={
 sources:[
 {name:'Gab’s teaching method & Zouk Atlas',url:'/method/',note:'The site’s own principles: understand, feel, practice, adapt; connection, timing and movement structure.'},
 {name:'Alex de Carvalho · MAC',url:'https://alexdecarvalho.com.br/brazilianzoukmac/',note:'Movement families, classroom pedagogy and connection. No MAC course content is reproduced.'},
 {name:'American Lambada Organization',url:'https://lambada.squarespace.com/curriculum',note:'Lambada-specific foundations, cultural context, role learning and repeated integration.'},
 {name:'District Zouk · Progression',url:'https://www.districtzouk.com/pages/progressive-classes-for-brazilian-zouk',note:'Progression based on observed skills and instructor assessment.'},
 {name:'Lamba London · Course structure',url:'https://www.lambalondon.co.uk/regular-classes',note:'An additional Lambada teaching perspective; levels and terminology vary by school.'}
 ],
 skills:[
 {id:'z-pulse',dance:'zouk',name:'Pulse & weight transfer',domain:'Rhythm',requires:[],goal:'Maintain a chosen Brazilian Zouk base timing while making clear weight transfers.',check:'Observe a short phrase without counting aloud, then change the music.',lead:'Offer timing without pushing a partner into a step.',follow:'Recognize your own support and complete each transfer.',atlas:'connection-3'},
 {id:'z-contact',dance:'zouk',name:'Connection & adjustable tone',domain:'Connection',requires:['z-pulse'],goal:'Share a simple change of direction through clear, responsive contact.',check:'Change partners and ask each dancer to describe the information they receive.',lead:'Prepare a direction and allow the response to unfold.',follow:'Respond while maintaining your own support.',atlas:'connection-0'},
 {id:'z-travel',dance:'zouk',name:'Frente–atrás & travelling basic',domain:'Pathways',requires:['z-pulse','z-contact'],goal:'Travel forward and back with consistent timing, space and weight commitment.',check:'Vary the travel distance without losing the base timing.',lead:'Choose a pathway that leaves room for both dancers.',follow:'Complete the weight change without anticipating the next direction.',atlas:'patterns-1'},
 {id:'z-lateral',dance:'zouk',name:'Lateral & changes of orientation',domain:'Pathways',requires:['z-travel'],goal:'Connect the chosen lateral pattern to a travelling basic with a clear change of orientation.',check:'Alternate the two pathways in an unfamiliar order.',lead:'Make the new direction legible before adding a variation.',follow:'Track orientation while retaining independent balance.',atlas:'patterns-5'},
 {id:'z-turn',dance:'zouk',name:'Simple turn & vertical axis',domain:'Turns',requires:['z-pulse','z-contact'],goal:'Enter and leave a simple upright turn with an organized axis and an unhurried exit.',check:'Use an agreed simple turn in a short dance and observe both preparation and recovery.',lead:'Make the invitation and exit clear without pulling through the turn.',follow:'Manage your own steps and balance through the rotation.',atlas:'patterns-8'},
 {id:'z-phrase',dance:'zouk',name:'Phrasing & choice',domain:'Musicality',requires:['z-pulse','z-travel'],goal:'Choose a familiar movement or pause in response to a musical phrase.',check:'Name the musical cue, then try a new track.',lead:'Leave time for a shared choice rather than filling every beat.',follow:'Express the music within the shared timing and space.',atlas:'awareness-0'},
 {id:'z-body',dance:'zouk',name:'Body pathways & isolations',domain:'Body organization',requires:['z-contact'],goal:'Explore a teacher-selected body pathway while preserving balance and responsive tone.',check:'Reduce the range and observe whether the same movement intention remains clear.',lead:'Distinguish an invitation from physically moving the partner’s body.',follow:'Choose a comfortable range and maintain your own organization.',atlas:'spirals-5'},
 {id:'z-head',dance:'zouk',name:'Head movement readiness',domain:'Teacher review',requires:['z-turn','z-body'],review:true,goal:'Record the prerequisites and adaptations for a head-movement lesson with a qualified teacher.',check:'Teacher observation determines whether to proceed, simplify or postpone.',lead:'Confirm consent and work only within the technique taught in person.',follow:'Retain the choice to keep the head neutral or stop.',atlas:'organization-1'},
 {id:'l-pulse',dance:'lambada',name:'Lambada pulse & weight changes',domain:'Rhythm',requires:[],goal:'Sustain a teacher-selected Lambada base timing with continuous, clear weight changes.',check:'Continue a simple basic through a short phrase with a new piece of music.',lead:'Offer the shared rhythm without forcing the partner’s speed.',follow:'Maintain independent weight changes within the shared timing.'},
 {id:'l-basic',dance:'lambada',name:'Basic pathways & openings',domain:'Foundations',requires:['l-pulse'],goal:'Connect an on-the-spot basic with selected openings or travelling pathways.',check:'Change the direction or size while preserving the Lambada rhythm.',lead:'Make the chosen opening visible through orientation and space.',follow:'Recognize the opening without abandoning your own steps.'},
 {id:'l-diagonal',dance:'lambada',name:'Diagonal preparation',domain:'Orientation',requires:['l-basic'],goal:'Recognize and communicate a diagonal preparation before a simple turn.',check:'Alternate a preparation with and without a turn so anticipation becomes visible.',lead:'Separate preparation from the decision to turn.',follow:'Respond to the preparation without automatically rotating.'},
 {id:'l-turn',dance:'lambada',name:'Upright turns & exits',domain:'Turns',requires:['l-diagonal'],goal:'Connect a teacher-selected simple turn back into a stable basic.',check:'Repeat with a different partner and observe the exit as carefully as the turn.',lead:'Preserve space and timing through the exit.',follow:'Keep independent support and choose a manageable rotation.'},
 {id:'l-soltinho',dance:'lambada',name:'Soltinho & shared pathways',domain:'Connection',requires:['l-diagonal','l-turn'],goal:'Explore a simple soltinho pathway with clear orientation and a connected return.',check:'Vary the entry while preserving the agreed relationship between partners.',lead:'Organize space rather than pulling a partner along a route.',follow:'Follow the shared pathway while maintaining your own rhythm.'},
 {id:'l-flow',dance:'lambada',name:'Flow, phrasing & integration',domain:'Musicality',requires:['l-basic','l-turn'],goal:'Link familiar basics and turns with continuity and an intentional response to the music.',check:'Dance a short phrase without a fixed sequence, then reflect on one transition.',lead:'Choose familiar transitions that fit the music and available space.',follow:'Stay responsive through transitions while contributing musical expression.'},
 {id:'l-head',dance:'lambada',name:'Boneca / head-movement readiness',domain:'Teacher review',requires:['l-turn','l-flow'],review:true,goal:'Plan a supervised readiness review before adding teacher-selected boneca or head-movement material.',check:'Record the teacher’s observations and a neutral-head alternative.',lead:'Agree on the movement and consent; avoid assuming a pattern is mandatory.',follow:'Keep the option to use a smaller range, neutral head or stop.'}
 ],
 drafts:{
 zouk:[['Find the pulse',['z-pulse'],'introduce'],['Share direction',['z-contact','z-pulse'],'practice'],['Travel with clarity',['z-travel'],'introduce'],['Change orientation',['z-lateral'],'practice'],['Turn and return',['z-turn'],'introduce'],['Connect choices to music',['z-phrase','z-travel','z-turn'],'transfer']],
 lambada:[['Ground the Lambada rhythm',['l-pulse'],'introduce'],['Open the pathways',['l-basic'],'introduce'],['Prepare the diagonal',['l-diagonal'],'practice'],['Turn and return',['l-turn'],'introduce'],['Explore soltinho',['l-soltinho'],'practice'],['Connect the flow',['l-flow','l-basic','l-turn'],'transfer']]
 }
};
