(() => {
'use strict';
const root=document.getElementById('teachingWorkbench');if(!root)return;
const KEY='gab-teaching-workbench-v1',status=document.getElementById('toolStatus'),saveState=document.getElementById('saveState');
const isCourse=root.dataset.tool==='curriculum-planner';
const empty=()=>({version:2,courses:[],sessions:[]});let db=empty(),selected=null,revision=0,userId=null,dirty=false,saving=null,timer=null,conflicted=false,editVersion=0;
const LIB=window.DANCE_PLANNER_LIBRARY;
const CURR=window.GAB_CURRICULUM||{concepts:[],families:[],concept:()=>null,displayName:id=>id,forFamily:()=>[],validIds:()=>[],prerequisites:()=>[],next:()=>[],sequence:()=>[],trackFits:()=>true};
const CLINKS=window.GAB_CURRICULUM_LINKS;
const DETAILS=window.ZOUK_DETAILS||{};
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID();const course=()=>db.courses.find(c=>c.id===selected);const session=()=>db.sessions.find(s=>s.id===selected);const list=c=>c.sessionIds.map(i=>db.sessions.find(s=>s.id===i)).filter(Boolean);
const trackFits=(concept,dance)=>concept&&(!CURR.trackFits||CURR.trackFits(concept,dance));
const allowedConcepts=dance=>(CURR.concepts||[]).filter(c=>trackFits(c,dance));
const cleanConceptIds=(ids,dance)=>[...new Set((CURR.validIds?CURR.validIds(ids):ids||[]).filter(cid=>trackFits(CURR.concept(cid),dance)))];
function valid(d){
 const text=x=>typeof x==='string'&&x.length<=10000,uid=x=>typeof x==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(x),number=x=>Number.isInteger(x)&&x>=0&&x<=1440;
 const idList=x=>x===undefined||(Array.isArray(x)&&x.length<=200&&x.every(v=>typeof v==='string'&&v.length<=100));
 if(!d||![1,2].includes(d.version)||!Array.isArray(d.courses)||!Array.isArray(d.sessions)||d.courses.length>100||d.sessions.length>500)return false;
 const all=[...d.courses,...d.sessions];if(all.some(x=>!x||!uid(x.id))||new Set(all.map(x=>x.id)).size!==all.length)return false;
 if(d.courses.some(c=>!['title','audience','goals','prerequisites','assessment'].every(k=>text(c[k]))||!Array.isArray(c.sessionIds)||new Set(c.sessionIds).size!==c.sessionIds.length||!idList(c.conceptIds)||!idList(c.knownConceptIds)))return false;
 if(d.sessions.some(s=>!['title','goal','learners','prerequisites','assessment','adaptations','reflection'].every(k=>text(s[k]))||!number(s.duration)||!(s.courseId===null||uid(s.courseId))||!Array.isArray(s.activities)||s.activities.length>100||s.activities.some(a=>!a||!uid(a.id)||!text(a.title)||!text(a.instructions)||!number(a.minutes))||new Set(s.activities.map(a=>a.id)).size!==s.activities.length||!idList(s.conceptIds)))return false;
 return d.courses.every(c=>c.sessionIds.every(i=>d.sessions.some(s=>s.id===i&&s.courseId===c.id)))&&d.sessions.every(s=>s.courseId===null?d.courses.every(c=>!c.sessionIds.includes(s.id)):d.courses.some(c=>c.id===s.courseId&&c.sessionIds.includes(s.id)));
}
function normalize(data){
 if(!valid(data))throw Error('Invalid plan data');
 data.version=2;
 for(const c of data.courses){
  c.dance=['zouk','lambada'].includes(c.dance)?c.dance:'zouk';c.level=['foundation','developing','experienced'].includes(c.level)?c.level:'foundation';
  c.knownSkills=Array.isArray(c.knownSkills)?c.knownSkills.filter(id=>LIB.skills.some(k=>k.id===id)):[];
  c.conceptIds=cleanConceptIds(c.conceptIds,c.dance);c.knownConceptIds=cleanConceptIds(c.knownConceptIds,c.dance);
 }
 for(const x of data.sessions){
  const c=data.courses.find(c=>c.id===x.courseId);x.dance=c?.dance||(['zouk','lambada'].includes(x.dance)?x.dance:'zouk');x.stage=['introduce','practice','revisit','transfer'].includes(x.stage)?x.stage:'introduce';
  x.skillIds=Array.isArray(x.skillIds)?x.skillIds.filter(id=>LIB.skills.some(k=>k.id===id)):[];x.conceptIds=cleanConceptIds(x.conceptIds,x.dance);
  for(const k of ['rhythm','music','bpm','readiness'])x[k]=typeof x[k]==='string'?x[k]:'';
  x.roleFocus=['both','leading','following'].includes(x.roleFocus)?x.roleFocus:'both';x.partnerMode=['rotating','fixed','solo'].includes(x.partnerMode)?x.partnerMode:'rotating';
 }
 return data;
}
const pendingKey=()=>userId?'gab-teacher-pending-'+userId:null;
function cache(){if(!pendingKey())return;try{if(dirty)localStorage.setItem(pendingKey(),JSON.stringify({document:db,revision}));else localStorage.removeItem(pendingKey());}catch{}}
function syncUI(message){saveState.textContent=message;document.getElementById('syncRetry').hidden=conflicted||!dirty;document.getElementById('syncReload').hidden=!conflicted;document.getElementById('syncBoth').hidden=!conflicted;}
function save(){if(!userId)return;dirty=true;editVersion++;cache();syncUI(conflicted?'Another version is saved. Choose how to keep your changes.':'Saving to your account…');clearTimeout(timer);if(!conflicted)timer=setTimeout(flush,550);}
async function flush(){clearTimeout(timer);if(conflicted)return false;if(saving){const ok=await saving;return ok&&dirty?flush():ok;}if(!dirty)return true;const sentVersion=editVersion,snapshot=JSON.parse(JSON.stringify(db));saving=(async()=>{try{const result=await TeacherCloud.save(snapshot,revision);revision=result.revision;dirty=sentVersion!==editVersion;cache();syncUI(dirty?'Saving your latest changes…':'Saved to your account');return true;}catch(error){conflicted=error.code==='40001';syncUI(conflicted?'A newer version was saved on another tab or device. Keep both or reload it.':'Not saved yet. Your changes remain here—check your connection and retry.');return false;}})();const ok=await saving;saving=null;if(ok&&dirty)return flush();return ok;}
window.TeacherPlannerFlush=flush;
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
document.addEventListener('click',async event=>{const link=event.target.closest('a[href]');if(!link||!userId||!dirty||event.ctrlKey||event.metaKey||event.shiftKey||link.target==='_blank'||link.hash&&link.pathname===location.pathname)return;event.preventDefault();if(await flush())location.href=link.href;});
document.getElementById('syncRetry').onclick=flush;
document.getElementById('syncReload').onclick=async()=>{if(!confirm('Load the saved account version and discard the unsaved changes on this page?'))return;try{const data=await TeacherCloud.read();db=normalize(data.document);revision=data.revision;dirty=false;conflicted=false;cache();render();syncUI('Loaded the saved account version.');}catch{syncUI('Could not load the saved version. Your changes are still here.');}};
document.getElementById('syncBoth').onclick=async()=>{try{const remote=await TeacherCloud.read(),merged=normalize(remote.document),copy=JSON.parse(JSON.stringify(db)),ids=new Map([...copy.courses,...copy.sessions].map(x=>[x.id,id()]));for(const c of copy.courses){c.id=ids.get(c.id);c.sessionIds=c.sessionIds.map(i=>ids.get(i));c.title+=' · recovered copy';}for(const x of copy.sessions){x.id=ids.get(x.id);x.courseId=ids.get(x.courseId)||null;}merged.courses.push(...copy.courses);merged.sessions.push(...copy.sessions);if(!valid(merged))throw Error();db=merged;revision=remote.revision;conflicted=false;selected=null;save();render();await flush();}catch{syncUI('Could not keep both versions yet. Your current changes are still here.');}};
function choose(value){selected=value;const u=new URL(location.href);if(value)u.searchParams.set(isCourse?'curriculum':'session',value);else u.searchParams.delete(isCourse?'curriculum':'session');history.replaceState(null,'',u);render();}
const fields=(obj,keys)=>keys.map(([key,label,type='text',hint=''])=>`<label class="${type==='area'?'wide':''}">${label}${type==='area'?`<textarea rows="3" maxlength="10000" data-field="${key}">${esc(obj[key])}</textarea>`:`<input ${type==='number'?'type="number" min="0" max="1440" step="1"':'maxlength="300"'} data-field="${key}" value="${esc(obj[key])}">`}${hint?`<small class="toolHint">${hint}</small>`:''}</label>`).join('');
function announce(text){status.textContent=text;}
function selectField(obj,key,label,choices,disabled=false){return `<label>${label}<select data-field="${key}" ${disabled?'disabled':''}>${choices.map(([value,text])=>`<option value="${value}" ${obj[key]===value?'selected':''}>${text}</option>`).join('')}</select></label>`;}
function skillChecks(obj,known){const picked=obj[known?'knownSkills':'skillIds'];return `<div class="skillChoices">${LIB.skills.filter(k=>k.dance===obj.dance).map(k=>`<label><input type="checkbox" data-skill="${k.id}" ${picked.includes(k.id)?'checked':''}><span>${esc(k.name)}<small>${esc(k.domain)}${k.review?' · teacher review':''}</small></span></label>`).join('')}</div>`;}
function skillGuidance(s){return s.skillIds.map(id=>{const k=LIB.skills.find(k=>k.id===id);if(!k)return '';return `<article class="skillGuide"><h3>${esc(k.name)}</h3><p><strong>Learning target:</strong> ${esc(k.goal)}</p><p><strong>Observe:</strong> ${esc(k.check)}</p><p><strong>Leading:</strong> ${esc(k.lead)}<br><strong>Following:</strong> ${esc(k.follow)}</p>${k.review?'<p class="readinessNote">This is a planning prompt for an in-person readiness review, not an instruction to perform head movements. A qualified teacher decides what is appropriate; keep a neutral-head alternative.</p>':''}${k.atlas?`<a href="/zouk-map/?concept=${encodeURIComponent(k.atlas)}#map">Explore related concept in your Zouk Atlas ↗</a>`:''}</article>`;}).join('');}
function activitiesFor(s){const skills=s.skillIds.map(id=>LIB.skills.find(k=>k.id===id)).filter(Boolean),focus=skills.filter(k=>!k.review);if(!focus.length)return [{id:id(),title:'Teacher readiness review',minutes:15,instructions:'Review the recorded prerequisites, consent and neutral-range alternatives with the teacher. Record an observation before deciding the next practice.'}];const one=focus[0];return [{id:id(),title:'Reconnect with rhythm & support',minutes:10,instructions:'Use the selected '+(s.dance==='lambada'?'Lambada':'Brazilian Zouk')+' timing. Begin with familiar steps and notice where the weight arrives.'},{id:id(),title:'Explore: '+one.name,minutes:15,instructions:one.goal+'\nLeading: '+one.lead+'\nFollowing: '+one.follow},{id:id(),title:'Practice with a clear focus',minutes:20,instructions:'Work on one selected skill at a time. Change partners or work solo as appropriate. Ask what information was clear and what needed adjustment.'},{id:id(),title:'Vary & observe',minutes:10,instructions:focus.map(k=>k.check).join(' ')},{id:id(),title:'Reflect & choose what to revisit',minutes:5,instructions:'Ask each dancer for one observation. Record a useful next practice rather than awarding a level from one successful attempt.'}];}
function conceptChecks(obj,key){
 const picked=new Set(obj[key]||[]),available=allowedConcepts(obj.dance);
 if(!available.length)return '<p class="toolHint">The canonical curriculum did not load. Your existing plan remains editable.</p>';
 return `<div class="conceptFamilies">${CURR.families.map(f=>{const items=available.filter(c=>c.family===f.id);if(!items.length)return '';const hasPicked=items.some(c=>picked.has(c.id));return `<details class="conceptFamily" ${hasPicked?'open':''}><summary>${esc(f.name)} · ${items.length}</summary><div class="skillChoices">${items.map(c=>`<label><input type="checkbox" data-concept="${c.id}" data-concept-set="${key}" ${picked.has(c.id)?'checked':''}><span>${esc(c.name)}<small>Depth ${c.tier} · ${esc(c.kind)}${c.track!=='shared'?' · '+esc(c.track):''}</small></span></label>`).join('')}</div></details>`;}).join('')}</div>`;
}
const nameList=items=>items.map(c=>esc(c.name)).join(', ');
function practiceAreas(ids){
 const rows=[],seen=new Set();
 for(const cid of ids||[])for(const link of CLINKS?.forConcept(cid)||[]){if(seen.has(link.skill))continue;seen.add(link.skill);rows.push(`<a class="toolLink" href="/zoukable/?skill=${encodeURIComponent(link.skill)}">${esc(link.name)} in Zoukable ↗</a>`);}
 return rows.length?`<p><strong>Related practice areas</strong></p><div class="toolRowActions">${rows.join('')}</div>`:'';
}
function courseGuidance(c){
 const chosen=c.conceptIds||[],known=new Set(c.knownConceptIds||[]);
 if(!chosen.length)return '<p class="toolHint">Choose target concepts above. The planner will surface supporting concepts, likely next branches and a dependency-aware teaching order.</p>';
 const supports=CURR.prerequisites(chosen,{recursive:true,track:c.dance}).filter(x=>!known.has(x.id));
 const next=CURR.next(chosen,{track:c.dance,limit:10});
 return `<div class="curriculumGuidance"><p><strong>${chosen.length} target concept${chosen.length===1?'':'s'}</strong> · canonical curriculum ${esc(CURR.version||'')}</p>${supports.length?`<p><strong>Supporting concepts to revisit or observe first:</strong> ${nameList(supports)}</p>`:'<p>No additional supporting concepts are implied by the current dependency map.</p>'}${next.length?`<p><strong>Likely next branches:</strong> ${nameList(next)}</p>`:''}${practiceAreas(chosen)}</div>`;
}
function availableBeforeSession(s){
 const c=db.courses.find(c=>c.id===s.courseId),available=new Set(c?.knownConceptIds||[]);
 if(c){for(const prior of list(c)){if(prior.id===s.id)break;for(const cid of prior.conceptIds||[])available.add(cid);}}
 return available;
}
function sessionGuidance(s){
 const chosen=s.conceptIds||[];if(!chosen.length)return '<p class="toolHint">Choose one or more curriculum concepts. The planner will show what supports them and what they can open next.</p>';
 const available=availableBeforeSession(s);
 const supports=CURR.prerequisites(chosen,{recursive:false,track:s.dance}).filter(x=>!available.has(x.id));
 const next=CURR.next(chosen,{track:s.dance,limit:8});
 const cards=chosen.map(cid=>{const c=CURR.concept(cid),d=DETAILS[cid];if(!c)return '';return `<article class="skillGuide"><p class="kicker">${esc(c.familyName)} · DEPTH ${c.tier}</p><h3>${esc(c.name)}</h3>${d?.understand?`<p>${esc(d.understand)}</p>`:''}${d?.notice?`<p><strong>Observe:</strong> ${esc(d.notice)}</p>`:''}<a href="/zouk-map/?concept=${encodeURIComponent(cid)}#map">Open in Atlas ↗</a></article>`;}).join('');
 return `${cards}${supports.length?`<p class="readinessNote"><strong>Support to check first:</strong> ${nameList(supports)}. This is guidance, not a hard gate or proof of readiness.</p>`:'<p class="toolHint">The currently recorded sequence contains the direct support concepts for this focus, or none are specified.</p>'}${next.length?`<p><strong>Possible next concepts:</strong> ${nameList(next)}</p>`:''}${practiceAreas(chosen)}`;
}
function conceptActivities(s){
 const focus=(s.conceptIds||[]).map(cid=>CURR.concept(cid)).filter(Boolean);if(!focus.length)return [];
 const missing=CURR.prerequisites(focus.map(c=>c.id),{recursive:false,track:s.dance}).filter(c=>!availableBeforeSession(s).has(c.id));
 const offaxis=focus.some(c=>c.family==='offaxis'),names=focus.map(c=>c.name).join(' + ');
 const understand=focus.map(c=>DETAILS[c.id]?.understand).filter(Boolean).join(' ');
 const notice=focus.map(c=>DETAILS[c.id]?.notice).filter(Boolean).join(' ');
 if(offaxis)return [
  {id:id(),title:'Readiness, consent & neutral option',minutes:10,instructions:'Confirm the teacher-observed prerequisites, consent, comfortable range and a neutral-head / on-axis alternative. Do not use this planner as a substitute for in-person technique or safety assessment.'},
  {id:id(),title:'Reconnect supporting foundations',minutes:10,instructions:missing.length?'Revisit: '+missing.map(c=>c.name).join(', ')+'. Use a familiar, comfortable task and check organization before adding complexity.':'Use a familiar, comfortable prerequisite task and confirm that support, timing and organization remain available.'},
  {id:id(),title:'Teacher-guided exploration: '+names,minutes:15,instructions:(understand||'Use the version taught in person.')+' Keep the exploration small enough to observe clearly; the neutral alternative remains available.'},
  {id:id(),title:'Vary one condition & observe',minutes:15,instructions:(notice||'Change only one variable and observe the result.')+' Keep the teacher-selected safety constraints unchanged.'},
  {id:id(),title:'Retrieve, reflect & choose next step',minutes:10,instructions:'Ask learners to describe the key organization from memory before reviewing. Record what remained reliable and what should be revisited next time.'}
 ];
 return [
  {id:id(),title:'Reconnect supporting concepts',minutes:8,instructions:missing.length?'Revisit: '+missing.map(c=>c.name).join(', ')+'. Use a familiar task to check these supports before adding the new focus.':'Retrieve a familiar foundation related to today’s focus before adding complexity.'},
  {id:id(),title:'Explore: '+names,minutes:12,instructions:understand||'Define the selected idea through a simple, observable task.'},
  {id:id(),title:'Practice one observable question',minutes:18,instructions:(notice||'Choose one observable question.')+' Give one correction at a time and allow enough repetitions for the learner to test the change.'},
  {id:id(),title:'Vary & transfer',minutes:15,instructions:'Change one condition—side, role, speed, range, partner setup or musical context—while keeping the main concept recognizable. Return to the simpler version if the foundation disappears.'},
  {id:id(),title:'Retrieve & reflect',minutes:7,instructions:'Before showing the answer again, ask learners to reconstruct the concept and one useful cue from memory. Record one question or practice focus for the next session.'}
 ];
}
function fillSuggestedPrerequisites(s){
 const available=availableBeforeSession(s);
 const supports=CURR.prerequisites(s.conceptIds||[],{recursive:false,track:s.dance}).filter(c=>!available.has(c.id));
 if(!supports.length)return false;
 const addition='Curriculum supports to revisit/check: '+supports.map(c=>c.name).join(', ')+'.';
 s.prerequisites=s.prerequisites.trim()?s.prerequisites.trim()+'\n'+addition:addition;return true;
}
function coverage(c){
 const sequence=list(c),seen=new Set(c.knownSkills),seenConcepts=new Set(c.knownConceptIds||[]),warnings=[];
 for(const [i,s] of sequence.entries()){
  for(const sid of s.skillIds){const k=LIB.skills.find(k=>k.id===sid);if(!k)continue;const missing=k.requires.filter(r=>!seen.has(r)&&!s.skillIds.includes(r));if(missing.length)warnings.push(`Session ${i+1}: consider ${missing.map(r=>LIB.skills.find(k=>k.id===r)?.name).join(', ')} before ${k.name}.`);if(k.review&&!s.readiness.trim())warnings.push(`Session ${i+1}: record a teacher readiness decision for ${k.name}.`);}
  s.skillIds.forEach(sid=>seen.add(sid));
  const current=new Set(s.conceptIds||[]);
  for(const cid of current){const concept=CURR.concept(cid);if(!concept)continue;const missing=concept.supports.filter(r=>CURR.concept(r)&&trackFits(CURR.concept(r),c.dance)&&!seenConcepts.has(r)&&!current.has(r));if(missing.length)warnings.push(`Session ${i+1}: ${concept.name} is supported by ${missing.map(r=>CURR.displayName(r)).join(', ')}. Consider observing or revisiting ${missing.length===1?'it':'them'} first.`);}
  current.forEach(cid=>seenConcepts.add(cid));
 }
 const targets=new Set(c.conceptIds||[]),covered=new Set(sequence.flatMap(s=>s.conceptIds||[]));
 for(const cid of targets)if(!covered.has(cid))warnings.push(`Curriculum target not yet assigned to a session: ${CURR.displayName(cid)}.`);
 const used=LIB.skills.filter(k=>k.dance===c.dance&&sequence.some(s=>s.skillIds.includes(k.id)));
 const usedConcepts=allowedConcepts(c.dance).filter(x=>sequence.some(s=>(s.conceptIds||[]).includes(x.id)));
 return `<section class="toolPanel" id="coveragePanel"><h2>Progression at a glance</h2><p class="toolHint">A planning check, not a student assessment. Earlier placement means “support this first,” not “master this completely.”</p>${warnings.length?`<details open><summary>${warnings.length} sequence question${warnings.length===1?'':'s'} to consider</summary><ul>${warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></details>`:'<p>No missing support prompts in the current sequence. Confirm readiness through observation.</p>'}${usedConcepts.length?`<h3>Canonical curriculum coverage</h3><div class="coverageRows">${usedConcepts.map(k=>`<div><strong>${esc(k.name)}</strong><span>${sequence.map((s,i)=>(s.conceptIds||[]).includes(k.id)?`<a href="/session-planner/?session=${s.id}">${i+1} · ${esc(s.stage)}</a>`:'').join('')}</span></div>`).join('')}</div>`:''}${used.length?`<h3>Practice-library skill coverage</h3><div class="coverageRows">${used.map(k=>`<div><strong>${esc(k.name)}</strong><span>${sequence.map((s,i)=>s.skillIds.includes(k.id)?`<a href="/session-planner/?session=${s.id}">${i+1} · ${esc(s.stage)}</a>`:'').join('')}</span></div>`).join('')}</div>`:''}${!used.length&&!usedConcepts.length?'<p>Choose curriculum concepts or movement skills inside your sessions to see their progression here.</p>':''}</section>`;
}
function sourcesPanel(){return `<details class="toolPanel"><summary>Teaching references &amp; how to use these drafts</summary><p>The canonical curriculum is Gab’s living model, informed by recurring Granola teaching evidence and dependency logic. The older practice-skill templates also draw on public dance-education references. These are editable planning supports, not standardized levels or readiness certification.</p>${LIB.sources.map(x=>`<p><a href="${x.url}" target="_blank" rel="noopener">${esc(x.name)} ↗</a><br>${esc(x.note)}</p>`).join('')}</details>`;}
function makeSession(c=null){const s={id:id(),courseId:c?.id||null,title:c?'Session '+(c.sessionIds.length+1):'Untitled session',duration:60,goal:'',learners:c?.audience||'',prerequisites:'',assessment:'',adaptations:'',reflection:'',dance:c?.dance||'zouk',stage:'introduce',skillIds:[],conceptIds:[],rhythm:'',music:'',bpm:'',roleFocus:'both',partnerMode:'rotating',readiness:'',activities:[]};db.sessions.push(s);if(c)c.sessionIds.push(s.id);return s;}
function render(){
 const items=isCourse?db.courses:db.sessions;const item=items.find(x=>x.id===selected);
 root.innerHTML=`<div class="toolToolbar"><label>${isCourse?'Your curricula':'Your sessions'}<select id="planSelect"><option value="">Choose a ${isCourse?'curriculum':'session'}</option>${items.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.title||'Untitled')}</option>`).join('')}</select></label><button class="toolPrimary" data-action="new">New ${isCourse?'curriculum':'standalone session'}</button></div>`;
 if(!item){root.insertAdjacentHTML('beforeend',`<div class="toolEmpty"><h2>${isCourse?'Start with the destination.':'Give your next lesson a structure.'}</h2><p>${isCourse?'Create a curriculum, choose concepts from Gab’s living curriculum, then build sessions in a dependency-aware order.':'Create a standalone session, or open a session from your curriculum. Select canonical concepts to see supporting ideas, likely next steps and practice links.'}</p><p class="toolHint">The canonical registry is shared with Atlas and Zoukable, so updated curriculum names and relationships appear here automatically.</p></div>`);return;}
 if(isCourse)renderCourse(item);else renderSession(item);
 root.insertAdjacentHTML('beforeend',`<div class="toolRowActions"><button class="toolDanger" data-action="deletePlan">Delete ${isCourse?'curriculum':'session'}</button></div>`);
}
function renderCourse(c){
 root.insertAdjacentHTML('beforeend',`<section class="toolPanel"><h2>The destination</h2><div class="toolFields">${selectField(c,'dance','Dance',[['zouk','Brazilian Zouk'],['lambada','Lambada']])}${selectField(c,'level','Teaching focus',[['foundation','Foundations'],['developing','Developing fluency'],['experienced','Experienced dancers']])}${fields(c,[['title','Curriculum title'],['audience','Learners and level'],['goals','Overall learning goals','area','What should learners be able to do by the end?'],['prerequisites','Starting point and prerequisites','area','What do learners need before this course?'],['assessment','How will you recognize progress?','area','Describe evidence of learning and when you will check it.']])}</div></section>
 <section class="toolPanel"><p class="kicker">LIVE CURRICULUM REGISTRY</p><h2>What should this curriculum develop?</h2><p class="toolHint">These concepts come from the same canonical registry used by Atlas and Zoukable. The relationship map suggests supports; it does not impose hard gates.</p>${conceptChecks(c,'conceptIds')}<div id="courseCurriculumGuidance">${courseGuidance(c)}</div><h3>Already observed at the start</h3><p class="toolHint">Mark concepts you have actually observed as available. This changes planning guidance only; it does not write student mastery or Atlas progress.</p>${conceptChecks(c,'knownConceptIds')}</section>
 <section class="toolPanel"><h2>Practice-library starting skills</h2><p class="toolHint">Keep these older dance-specific skill signals when useful. They can coexist with the canonical concept model.</p>${skillChecks(c,true)}</section>
 <section class="toolPanel"><h2>The progression</h2><div class="toolRowActions"><button class="toolPrimary" data-action="conceptDraft">Draft sessions from selected curriculum concepts</button><button data-action="draft">Add an editable ${c.dance==='lambada'?'Lambada':'Zouk'} foundation template</button></div><p class="toolHint">Curriculum-based drafting follows concept depth and dependency relationships. Every generated session remains fully editable.</p><p>Give each session a focused goal. Use the arrows to adjust the sequence, then open a session to plan its activities.</p><p class="toolCount">${c.sessionIds.length} sessions · ${list(c).reduce((n,s)=>n+s.duration,0)} planned minutes</p><ol class="toolRows">${list(c).map((s,i)=>`<li class="toolRow"><div class="toolRowTop"><div><p class="kicker">Session ${i+1}</p><h3>${esc(s.title)}</h3></div><span>${s.duration} min · ${esc(s.stage)} · ${s.activities.length} activities</span></div><p>${esc(s.goal||'No learning goal yet—open this session to define it.')}</p>${s.conceptIds?.length?`<p class="toolHint">${s.conceptIds.map(cid=>esc(CURR.displayName(cid))).join(' · ')}</p>`:''}<div class="toolRowActions"><a class="toolLink" href="/session-planner/?session=${s.id}">Plan session →</a><button data-action="up" data-id="${s.id}" ${i===0?'disabled':''} aria-label="Move session ${i+1} earlier">↑ Earlier</button><button data-action="down" data-id="${s.id}" ${i===c.sessionIds.length-1?'disabled':''} aria-label="Move session ${i+1} later">↓ Later</button><button data-action="detach" data-id="${s.id}">Make standalone</button></div></li>`).join('')}</ol><button class="toolPrimary" data-action="addSession">Add a session</button></section>${coverage(c)}${sourcesPanel()}`);
}
function renderSession(s){
 const c=db.courses.find(c=>c.id===s.courseId);
 root.insertAdjacentHTML('beforeend',`<div class="toolContext">${c?`<strong>Part of: ${esc(c.title)}</strong> · Session ${c.sessionIds.indexOf(s.id)+1} of ${c.sessionIds.length}<br><a href="/curriculum-planner/?curriculum=${c.id}">← Return to the curriculum</a><p><strong>Overall goals</strong><br>${esc(c.goals||'No overall goals defined yet.')}</p><p><strong>Course prerequisites</strong><br>${esc(c.prerequisites||'Not yet defined.')}</p>`:'<strong>Standalone session</strong><p>You can plan this independently or connect it to a curriculum below.</p>'}<label>Curriculum<select id="attachCourse"><option value="">Standalone</option>${db.courses.map(c=>`<option value="${c.id}" ${s.courseId===c.id?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label></div>
 <section class="toolPanel"><h2>The session</h2><div class="toolFields">${selectField(s,'dance','Dance',[['zouk','Brazilian Zouk'],['lambada','Lambada']],!!c)}${selectField(s,'stage','Learning stage',[['introduce','Introduce'],['practice','Practice'],['revisit','Revisit'],['transfer','Transfer']])}${fields(s,[['title','Session title'],['duration','Planned duration (minutes)','number'],['goal','Session learning goal','area','What will learners be able to do by the end?'],['learners','Learners and starting point','area'],['prerequisites','What will you revisit or check first?','area'],['assessment','Evidence of learning and transfer','area','How will you check that learners can use the skill beyond this exercise?']])}</div></section>
 <section class="toolPanel"><p class="kicker">LIVE CURRICULUM REGISTRY</p><h2>Curriculum focus</h2><p class="toolHint">Select the concepts this class is actually trying to develop. The planner will surface supporting concepts, Atlas definitions, next branches and linked Zoukable practice areas.</p>${conceptChecks(s,'conceptIds')}<div id="sessionCurriculumGuidance">${sessionGuidance(s)}</div><div class="toolRowActions"><button class="toolPrimary" data-action="conceptActivities">Add curriculum-based activities</button><button data-action="fillPrerequisites">Add suggested supports to prerequisite notes</button></div></section>
 <section class="toolPanel"><h2>Practice-library &amp; musical focus</h2>${skillChecks(s,false)}<div id="skillGuidance">${skillGuidance(s)}</div><div class="toolFields">${fields(s,[['rhythm','Timing / rhythm reference'],['bpm','Practice tempo (BPM, if useful)'],['music','Track, artist or music link','area'],['readiness','Readiness, consent and alternatives','area','Record what you have observed and how dancers can simplify, opt out or stay in a neutral range.']])}${selectField(s,'roleFocus','Role focus',[['both','Both roles'],['leading','Leading'],['following','Following']])}${selectField(s,'partnerMode','Practice format',[['rotating','Rotating partners'],['fixed','Fixed partners'],['solo','Solo practice']])}</div><button data-action="skillActivities">Add activities for selected practice skills</button></section>
 <section class="toolPanel"><h2>Activities &amp; timing</h2><p class="toolHint">Build the session in the order you will teach it. Each activity has a purpose, instructions and an editable duration.</p><p id="timeSummary" class="timeSummary"></p><ol class="toolRows">${s.activities.map((a,i)=>`<li class="toolRow"><div class="toolFields"><label>Activity ${i+1}<input maxlength="300" data-activity="${a.id}" data-field="title" value="${esc(a.title)}"></label><label>Minutes<input type="number" min="0" max="1440" step="1" data-activity="${a.id}" data-field="minutes" value="${a.minutes}"></label><label class="wide">Purpose, instructions &amp; feedback<textarea rows="3" maxlength="10000" data-activity="${a.id}" data-field="instructions">${esc(a.instructions)}</textarea></label></div><div class="toolRowActions"><button data-action="activityUp" data-id="${a.id}" ${i===0?'disabled':''}>↑ Earlier</button><button data-action="activityDown" data-id="${a.id}" ${i===s.activities.length-1?'disabled':''}>↓ Later</button><button class="toolDanger" data-action="removeActivity" data-id="${a.id}">Remove activity</button></div></li>`).join('')}</ol><div class="toolRowActions"><button class="toolPrimary" data-action="addActivity">Add an activity</button>${!s.activities.length?'<button data-action="starter">Use a 60-minute structure</button>':''}</div><p class="toolHint">Adapt each practice to the dancers in front of you. Curriculum relationships are planning prompts, not automatic readiness judgments.</p></section>
 <section class="toolPanel"><h2>Adapt &amp; reflect</h2><div class="toolFields">${fields(s,[['adaptations','Adaptations and alternatives','area','How could you simplify, add a challenge or adjust for different needs?'],['reflection','Notes after teaching','area','What did you observe? What will you revisit or change next time?']])}</div></section>`);updateTime();
}
function updateTime(){const s=session(),el=document.getElementById('timeSummary');if(!s||!el)return;const total=s.activities.reduce((n,a)=>n+a.minutes,0),diff=s.duration-total;el.textContent=`${total} / ${s.duration} minutes planned · ${diff===0?'Timing matches':diff>0?diff+' minutes unallocated':-diff+' minutes over target'}`;el.classList.toggle('over',diff<0);}
function refreshCurriculumGuidance(item){
 if(isCourse){const g=document.getElementById('courseCurriculumGuidance');if(g)g.innerHTML=courseGuidance(item);const p=document.getElementById('coveragePanel');if(p)p.outerHTML=coverage(item);}
 else{const g=document.getElementById('sessionCurriculumGuidance');if(g)g.innerHTML=sessionGuidance(item);}
}
root.addEventListener('input',e=>{if(e.target.matches('select')||e.target.dataset.skill||e.target.dataset.concept)return;const key=e.target.dataset.field;if(!key)return;const item=isCourse?course():session();const target=e.target.dataset.activity?item.activities.find(a=>a.id===e.target.dataset.activity):item;if(!target||!Object.hasOwn(target,key))return;const numeric=key==='duration'||key==='minutes';if(numeric&&!e.target.validity.valid)return;target[key]=numeric?Number(e.target.value):e.target.value;save();if(key==='title'&&!e.target.dataset.activity){const option=[...document.getElementById('planSelect').options].find(o=>o.value===selected);if(option)option.textContent=target.title||'Untitled';}updateTime();});
root.addEventListener('change',e=>{
 if(e.target.dataset.concept){
  const item=isCourse?course():session(),key=e.target.dataset.conceptSet;
  item[key]=[...root.querySelectorAll(`[data-concept-set="${key}"]:checked`)].map(x=>x.dataset.concept);save();refreshCurriculumGuidance(item);return;
 }
 if(e.target.dataset.skill){const item=isCourse?course():session(),key=isCourse?'knownSkills':'skillIds';item[key]=[...root.querySelectorAll('[data-skill]:checked')].map(x=>x.dataset.skill);save();if(isCourse){const el=document.getElementById('coveragePanel');if(el)el.outerHTML=coverage(item);}else document.getElementById('skillGuidance').innerHTML=skillGuidance(item);return;}
 if(e.target.matches('select[data-field]')){
  const item=isCourse?course():session(),key=e.target.dataset.field;
  const nextDance=e.target.value,specificConcepts=key==='dance'?[...(item.conceptIds||[]),...(isCourse?item.knownConceptIds||[]:[])].some(cid=>{const cc=CURR.concept(cid);return cc&&cc.track!=='shared'&&!trackFits(cc,nextDance);}):false;
  if(key==='dance'&&((isCourse&&(item.knownSkills.length||list(item).some(s=>s.skillIds.length)))||(!isCourse&&item.skillIds.length)||specificConcepts)&&!confirm('Changing the dance clears dance-specific practice skills and curriculum concepts that do not belong to the new track. Written notes and shared concepts will be kept. Continue?')){e.target.value=item[key];return;}
  item[key]=e.target.value;
  if(key==='dance'){
   if(isCourse){item.knownSkills=[];item.conceptIds=cleanConceptIds(item.conceptIds,item.dance);item.knownConceptIds=cleanConceptIds(item.knownConceptIds,item.dance);list(item).forEach(x=>{x.dance=item.dance;x.skillIds=[];x.conceptIds=cleanConceptIds(x.conceptIds,x.dance);});}
   else{item.skillIds=[];item.conceptIds=cleanConceptIds(item.conceptIds,item.dance);}
  }
  save();render();return;
 }
 if(e.target.id==='planSelect')choose(e.target.value||null);
 if(e.target.id==='attachCourse'){const s=session();db.courses.forEach(c=>c.sessionIds=c.sessionIds.filter(i=>i!==s.id));s.courseId=e.target.value||null;const c=db.courses.find(c=>c.id===s.courseId);if(c){c.sessionIds.push(s.id);if(s.dance!==c.dance){s.dance=c.dance;s.skillIds=[];s.conceptIds=cleanConceptIds(s.conceptIds,s.dance);}}save();render();announce('Session connection updated.');}
});
function move(arr,from,delta){const to=from+delta;if(from>=0&&to>=0&&to<arr.length)[arr[from],arr[to]]=[arr[to],arr[from]];}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const action=btn.dataset.action,ref=btn.dataset.id,c=course(),s=session();
 if(action==='new'){if((isCourse&&db.courses.length>=100)||(!isCourse&&db.sessions.length>=500)){announce('You have reached the plan limit. Remove unused plans to continue.');return;}if(isCourse){const c={id:id(),title:'Untitled curriculum',dance:'zouk',level:'foundation',knownSkills:[],knownConceptIds:[],conceptIds:[],audience:'',goals:'',prerequisites:'',assessment:'',sessionIds:[]};db.courses.push(c);selected=c.id;}else selected=makeSession().id;save();choose(selected);return;}
 if(action==='conceptDraft'){
  if(!c.conceptIds.length){announce('Choose at least one canonical curriculum concept first.');return;}
  const ordered=CURR.sequence(c.conceptIds),limit=Math.min(ordered.length,12);if(db.sessions.length+limit>500){announce('Too many sessions to create this curriculum draft.');return;}
  for(const concept of ordered.slice(0,limit)){const x=makeSession(c),d=DETAILS[concept.id];x.title=concept.name;x.conceptIds=[concept.id];x.stage=concept.tier<=2?'introduce':'practice';x.goal=d?.understand||`Develop a usable understanding of ${concept.name}.`;x.assessment=d?.notice||`Observe whether learners can use ${concept.name} when one condition changes.`;const supports=CURR.prerequisites([concept.id],{recursive:false,track:c.dance});x.prerequisites=supports.length?'Revisit/check: '+supports.map(q=>q.name).join(', ')+'.':'';x.activities=conceptActivities(x);x.duration=x.activities.reduce((n,a)=>n+a.minutes,0);}
  if(ordered.length>limit)announce(`Drafted the first ${limit} concepts in dependency order. Add the remaining targets in another pass.`);else announce('Curriculum-based session draft added.');
 }
 if(action==='draft'){if(db.sessions.length+6>500){announce('Too many sessions to add a progression.');return;}for(const [title,skills,stage] of LIB.drafts[c.dance]){const x=makeSession(c);x.title=title;x.skillIds=skills;x.stage=stage;x.goal=skills.map(id=>LIB.skills.find(k=>k.id===id).goal).join(' ');x.assessment=skills.map(id=>LIB.skills.find(k=>k.id===id).check).join(' ');x.activities=activitiesFor(x);x.duration=x.activities.reduce((n,a)=>n+a.minutes,0);}if(!c.goals)c.goals=c.dance==='lambada'?'Maintain Lambada timing, organize shared pathways and connect familiar movements with continuity.':'Share timing and direction, connect basic pathways and adapt familiar movement to a partner and music.';if(!c.assessment)c.assessment='Observe a short social dance, vary one condition and use the next lesson to revisit what needs attention.';}
 if(action==='conceptActivities'){if(!s.conceptIds.length){announce('Choose at least one curriculum concept first.');return;}const acts=conceptActivities(s);if(s.activities.length+acts.length>100){announce('This session has reached its activity limit.');return;}s.activities.push(...acts);}
 if(action==='fillPrerequisites'){if(!s.conceptIds.length){announce('Choose at least one curriculum concept first.');return;}if(!fillSuggestedPrerequisites(s)){announce('The direct support concepts are already represented earlier in this curriculum, or none are specified.');return;}}
 if(action==='skillActivities'){if(!s.skillIds.length){announce('Choose at least one skill first.');return;}const acts=activitiesFor(s);if(s.activities.length+acts.length>100){announce('This session has reached its activity limit.');return;}s.activities.push(...acts);}
 if(action==='addSession'){if(db.sessions.length>=500){announce('Organize your current plans before adding more sessions.');return;}makeSession(c);}
 if(action==='up'||action==='down')move(c.sessionIds,c.sessionIds.indexOf(ref),action==='up'?-1:1);
 if(action==='detach'){c.sessionIds=c.sessionIds.filter(i=>i!==ref);db.sessions.find(s=>s.id===ref).courseId=null;}
 if(action==='addActivity'&&s.activities.length>=100){announce('This session has reached the 100-activity limit.');return;}
 if(action==='addActivity')s.activities.push({id:id(),title:'New activity',minutes:10,instructions:''});
 if(action==='starter')s.activities=[['Observe & prepare',5],['Explore the idea',15],['Guided practice',20],['Vary & transfer',15],['Reflect & choose a next step',5]].map(([title,minutes])=>({id:id(),title,minutes,instructions:''}));
 if(action==='activityUp'||action==='activityDown')move(s.activities,s.activities.findIndex(a=>a.id===ref),action==='activityUp'?-1:1);
 if(action==='removeActivity'){if(!confirm('Remove this activity from the session?'))return;s.activities=s.activities.filter(a=>a.id!==ref);}
 if(action==='deletePlan'){if(!confirm(isCourse?'Delete this curriculum? Its sessions will remain in your account as standalone plans.':'Delete this session and its activities from your account? This cannot be undone.'))return;if(isCourse){list(c).forEach(s=>s.courseId=null);db.courses=db.courses.filter(x=>x.id!==c.id);}else{db.courses.forEach(c=>c.sessionIds=c.sessionIds.filter(i=>i!==s.id));db.sessions=db.sessions.filter(x=>x.id!==s.id);}selected=null;}
 save();render();if(!['conceptDraft','fillPrerequisites'].includes(action))announce('Plan updated.');
});
window.addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
async function boot(){try{const {workspace,userId:uid}=await TeacherCloud.load();userId=uid;db=normalize(workspace.document);revision=workspace.revision;let pending=null;try{pending=JSON.parse(localStorage.getItem(pendingKey())||'null');}catch{}if(pending&&valid(pending.document)){db=normalize(pending.document);dirty=true;conflicted=pending.revision!==revision;}const requested=new URLSearchParams(location.search).get(isCourse?'curriculum':'session');selected=(isCourse?db.courses:db.sessions).some(x=>x.id===requested)?requested:null;render();document.getElementById('syncControls').hidden=false;syncUI(conflicted?'Unsaved changes from this device overlap a newer account version. Keep both or reload.':dirty?'Restoring your unsaved changes…':'Saved to your account');if(dirty&&!conflicted)flush();if(requested&&!selected)announce('This plan is not available in your account. Choose a plan above.');offerLegacy();}catch{root.textContent='Your plans could not be loaded. Refresh to try again; saved account plans have not been changed.';}}
function offerLegacy(){try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(!old||!valid(old)||(!old.courses.length&&!old.sessions.length))return;const el=document.createElement('div');el.className='toolContext';el.innerHTML=`<p>${old.courses.length} curricula and ${old.sessions.length} sessions from the earlier planner are on this device.</p><button id="bringDrafts">Add these drafts to my account</button><p class="toolHint">Only do this if these are your plans. Existing account plans will be kept.</p>`;document.getElementById('accountBar').after(el);let added=false;document.getElementById('bringDrafts').onclick=async()=>{const button=document.getElementById('bringDrafts');button.disabled=true;if(added){if(await flush()){localStorage.removeItem(KEY);el.remove();}else button.disabled=false;return;}const copy=normalize(JSON.parse(JSON.stringify(old))),ids=new Map([...copy.courses,...copy.sessions].map(x=>[x.id,id()]));copy.courses.forEach(c=>{c.id=ids.get(c.id);c.sessionIds=c.sessionIds.map(i=>ids.get(i));});copy.sessions.forEach(s=>{s.id=ids.get(s.id);s.courseId=ids.get(s.courseId)||null;});const merged={...db,courses:[...db.courses,...copy.courses],sessions:[...db.sessions,...copy.sessions]};if(!valid(merged)){announce('These drafts exceed the workspace limit.');button.disabled=false;return;}db=merged;added=true;save();render();if(await flush()){localStorage.removeItem(KEY);el.remove();announce('Your earlier drafts are now saved to your account.');}else{button.disabled=false;button.textContent='Retry saving these drafts';}};}catch{}}
boot();
})();
