(()=>{'use strict';
const host=document.getElementById('training-inquiry');if(!host)return;
const settings={classes:{title:'Let’s find your class.',intro:'Tell Gab where you are in your dancing and what you would like to explore.',options:['Tuesday Brazilian Zouk','Thursday Lambada','Help me choose a class'],timing:'When would you like to join?',hint:'Include the date you have in mind. Gab will help confirm the right level.'},privates:{title:'What would you like to work on?',intro:'A few details help Gab suggest a useful focus for your session.',options:['Private coaching · 1 hour','Kinesthetic practice · 30 minutes','Help me choose a format'],timing:'What times could work for you?',hint:'Two or three options help. Availability and location are confirmed with Gab.'},stay:{title:'Plan your stay and training.',intro:'Share your dates and dance goals to start planning your visit.',options:['Weekend stay & training','Weekly stay & training','Monthly stay & training','Help me choose a stay'],timing:'Travel dates and number of guests',hint:'Include your arrival and departure dates, and how many people will stay.'}};
const config=settings[host.dataset.inquiry];if(!config)return;
host.innerHTML=`<div class="w inquiryLayout"><div><p class="inquiryKicker">Your next step</p><h2 id="inquiry-title">${config.title}</h2><p>${config.intro}</p><p class="inquiryNote">You’ll review your message before sending. This is an inquiry; your place or booking is confirmed separately with Gab.</p><p class="inquiryDirect">Prefer a direct conversation?<br><a href="https://wa.me/19295864994" target="_blank" rel="noopener">WhatsApp Gab</a> · <a href="mailto:hello@gablacarriere.com">Email Gab</a></p></div><form id="trainingInquiryForm"><label for="inquiry-name">Your name *</label><input id="inquiry-name" name="name" required maxlength="100" autocomplete="name"><label for="inquiry-interest">I’m interested in</label><select id="inquiry-interest" name="interest">${config.options.map(o=>'<option>'+o+'</option>').join('')}</select><label for="inquiry-experience">Dance experience</label><select id="inquiry-experience" name="experience"><option>Prefer to discuss with Gab</option><option>New to partner dance</option><option>New to Zouk / Lambada, with other dance experience</option><option>Less than 1 year of Zouk / Lambada</option><option>1–3 years of Zouk / Lambada</option><option>More than 3 years of Zouk / Lambada</option></select><label for="inquiry-goal">Your goal or question *</label><textarea id="inquiry-goal" name="goal" required maxlength="700" rows="3" placeholder="For example: I want to feel more comfortable with different partners."></textarea><label for="inquiry-timing">${config.timing}</label><input id="inquiry-timing" name="timing" maxlength="200" aria-describedby="inquiry-timing-help"><small id="inquiry-timing-help">${config.hint}</small><button class="inquiryPrimary" type="submit">Review my message →</button><section id="inquiry-draft" hidden aria-labelledby="inquiry-draft-title"><h3 id="inquiry-draft-title" tabindex="-1">Ready for you to send.</h3><label for="inquiry-message">Your message</label><textarea id="inquiry-message" rows="9" readonly></textarea><div class="inquiryActions"><a id="inquiry-whatsapp" target="_blank" rel="noopener" class="inquiryPrimary">Continue in WhatsApp ↗</a><a id="inquiry-email">Open email app</a><button id="inquiry-copy" type="button">Copy message</button></div><small>Nothing has been sent yet. Press Send in WhatsApp or your email app. If neither opens, copy the message and email hello@gablacarriere.com.</small></section><p id="inquiry-status" role="status" aria-live="polite"></p></form></div>`;
const $=id=>document.getElementById(id),form=$('trainingInquiryForm');
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;
const name=$('inquiry-name').value.trim(),goal=$('inquiry-goal').value.trim();
if(!name||!goal){$('inquiry-status').textContent='Please add your name and a short goal or question.';return;}
const message=`Hi Gab, I’m ${name}.\n\nI’m interested in: ${$('inquiry-interest').value}.\nDance experience: ${$('inquiry-experience').value}.\n\nMy goal or question:\n${goal}\n\n${config.timing}: ${$('inquiry-timing').value.trim()||'To discuss'}.\n\nCould you help me with the next step?`;
$('inquiry-message').value=message;$('inquiry-whatsapp').href='https://wa.me/19295864994?text='+encodeURIComponent(message);$('inquiry-email').href='mailto:hello@gablacarriere.com?subject='+encodeURIComponent($('inquiry-interest').value+' inquiry')+'&body='+encodeURIComponent(message);$('inquiry-draft').hidden=false;$('inquiry-status').textContent='Message prepared. Choose how to send it below.';$('inquiry-draft-title').focus();
});
form.addEventListener('input',e=>{if(e.target.id!=='inquiry-message'){$('inquiry-draft').hidden=true;$('inquiry-status').textContent='';}});
$('inquiry-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('inquiry-message').value);$('inquiry-status').textContent='Message copied. Paste it into your conversation with Gab.';}catch(_){$('inquiry-message').focus();$('inquiry-message').select();$('inquiry-status').textContent='Select and copy the message above.';}});
})();
