(() => {
'use strict';
const groups=window.ZOUK_ATLAS,details=window.ZOUK_DETAILS;
const nodes=groups.flatMap(g=>g.topics.map((name,i)=>({id:g.id+'-'+i,name,group:g})));
let progress={'organization-0':'Introduced','steps-1':'Practicing'},approved=false,selected='organization-0',region='All',search='';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=id=>progress[id]||'Unexplored';
const content=document.getElementById('content');
const announcement=document.getElementById('announcement');
function nodeLink(id,label){return `<button class="topic ${progress[id]?'discovered':''}" data-node="${id}" aria-pressed="${id===selected}">${esc(label)}</button>`;}
function title(kicker,name,body){return `<div class="topline"><div><p class="eyebrow">${kicker}</p><h1>${name}</h1><p>${body}</p></div><div class="count"><b>${Object.keys(progress).length} / ${nodes.length}</b>concepts explored<br>sample journey</div></div>`;}
function map(){
 content.innerHTML=title('02 / EXPLORE','My Zouk map','Follow a constellation. Open a concept. See how it connects to your practice.')+`<div class="toolbar" role="group" aria-label="Curriculum region">${['All','Foundations','Bridge','Movement Patterns'].map(r=>`<button class="filter" data-region="${r}" aria-pressed="${region===r}">${r}</button>`).join('')}</div><label class="sr" for="conceptSearch">Find a concept</label><input type="search" id="conceptSearch" class="search" placeholder="Find a concept — try breath, lateral or spiral" value="${esc(search)}"><div class="legend"><span><b>✧</b>Unexplored</span><span><b>✦</b>Introduced / Practicing</span><span>Integration is confirmed by Gab, not by a click.</span></div><div class="mapLayout"><div id="constellations" class="constellations"></div><aside id="detail" class="detail" aria-label="Selected concept" tabindex="-1"></aside></div><p class="mapFootnote">Draft grouping. Lines suggest relationships within a constellation; they are not prerequisites or a required teaching order. All concepts remain explorable.</p>`;
 renderGroups();renderDetail();
 document.getElementById('conceptSearch').addEventListener('input',e=>{search=e.target.value;renderGroups();});
}
function renderGroups(){
 const filtered=groups.filter(g=>(region==='All'||g.region===region)&&g.topics.some(n=>n.toLowerCase().includes(search.toLowerCase())));
 document.getElementById('constellations').innerHTML=filtered.map(g=>{
 const items=nodes.filter(n=>n.group===g&&n.name.toLowerCase().includes(search.toLowerCase()));
 const points=items.map((_,i)=>[12+(i%5)*19,20+Math.floor(i/5)*21+(i%2)*9]);
 return `<article class="constellation" style="--star:${g.color}"><p class="eyebrow">${g.region}</p><h3>${g.name}</h3><p class="intro">${g.intro}</p><div class="starfield"${items.length>10?' style="height:220px"':''}><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="${points.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ')}"/></svg>${items.map((n,i)=>`<button class="star ${progress[n.id]?'discovered':'unexplored'}" style="left:${points[i][0]}%;top:${points[i][1]}%" data-node="${n.id}" aria-label="${esc(n.name)} — ${status(n.id)}" aria-pressed="${n.id===selected}" title="${esc(n.name)}">${progress[n.id]?'✦':'✧'}</button>`).join('')}</div><div class="topicList">${items.map(n=>nodeLink(n.id,n.name)).join('')}</div></article>`;
 }).join('')||'<p class="empty">No matching concepts in this region. Try a different word or choose All.</p>';
}
function renderDetail(){
 const n=nodes.find(n=>n.id===selected),d=details[n.id];
 const inLesson=['organization-1','connection-1','patterns-5'].includes(n.id)&&approved;
 const related=nodes.filter(x=>x.group===n.group&&x.id!==n.id).slice(0,3);
 document.getElementById('detail').innerHTML=`<p class="eyebrow">${n.group.name}</p><span class="badge ${progress[n.id]?'lit':''}">${status(n.id)}</span><h2>${esc(n.name)}</h2><p>${d?.understand?esc(d.understand):'Named in Gab’s draft curriculum. The individual lesson explanation is still to be developed.'}</p>${d?.notice?`<section><h4>What to notice</h4><p>${esc(d.notice)}</p></section>`:''}<section><h4>My practice</h4><p>${inLesson?'Sample task: explore the lateral with adjustable tone. Notice whether a change of direction requires a reset. This proposed exercise is for demonstrating the prototype.':'No personal exercise assigned in this sample. A reviewed lesson can connect this concept to your practice.'}</p>${inLesson?'<a class="secondaryButton" href="#practice">Open sample practice →</a>':''}</section><section><h4>My journey</h4><p>${inLesson?'Introduced or practiced in Sample private 01. Added after the demo review.':progress[n.id]?'Illustrative starting progress. This is not a record of a real lesson.':'Not yet explored in this sample. You can still read the concept.'}</p></section>${related.length?`<section><h4>In this constellation</h4><div class="topicList">${related.map(x=>nodeLink(x.id,x.name)).join('')}</div></section>`:''}${n.group.principle?`<details><summary>Go deeper · Gab’s draft</summary><p>${esc(n.group.principle)}</p><p>Constellation-level principle, not a complete definition of every concept here.</p></details>`:''}`;
}
function journey(){content.innerHTML=title('01 / YOUR DIRECTION','My journey','One place to find your focus, your latest discoveries and your next step.')+`<div class="box focusBox wide"><p class="sampleLabel">Sample student journey</p><h2>${approved?'From adjustable tone to an adaptable lateral.':'Begin with availability.'}</h2><p>${approved?'Your reviewed sample lesson connects body organization, permeability and a movement pattern.':'This sample starts with breathing and footwork. Review the example private lesson to see three more concepts appear on your map.'}</p><a class="primaryButton" href="${approved?'#practice':'#sessions'}">${approved?'Open my practice':'Review the sample lesson'} →</a></div><div class="cards wide"><section class="box"><h3>Your discoveries</h3><p>${Object.keys(progress).length} concepts explored. No percentage of mastery: discovery and integration are different steps.</p><a class="secondaryButton" href="#map">Explore my map →</a></section><section class="box"><h3>A connected learning loop</h3><p>Lesson → reviewed discoveries → focused practice → feedback in the next lesson.</p><p>Your map can grow while familiar concepts remain part of your practice.</p></section></div>`;}
function practice(){content.innerHTML=title('03 / BETWEEN LESSONS','My practice','A focused task connected to the concepts you are exploring.')+(approved?`<article class="box wide"><p class="sampleLabel">Illustrative exercise · Sample private 01</p><h2>Availability in the lateral</h2><p>Explore the lateral with adjustable tone. Notice whether a change of direction requires a reset.</p><ul><li>What changes when you use less unnecessary effort?</li><li>What helps information travel through the connection?</li><li>What would you like Gab to observe next time?</li></ul><p>This exercise demonstrates the experience; it is not a real assignment or a completed assessment.</p><div class="topicList">${['organization-1','connection-1','patterns-5'].map(id=>nodeLink(id,nodes.find(n=>n.id===id).name)).join('')}</div></article>`:`<div class="box wide"><h2>No sample assignment yet.</h2><p>Open Sessions and review the example lesson. Its exercise and related concepts will appear here after approval.</p><a class="primaryButton" href="#sessions">Open the sample lesson →</a></div>`);}
function sessions(){content.innerHTML=title('04 / LESSON HISTORY','My sessions','See what was explored, what was reviewed and what to practice next.')+`<article class="box wide"><p class="sampleLabel">Demo coach review · Not a Granola import</p><h2>Sample private 01</h2><div class="sessionNote"><p>“We explored adjustable tone, introduced permeability and practiced the lateral. The focus was changing direction without a preparatory reset.”</p><small>Invented lesson summary to demonstrate the workflow.</small></div><h3>${approved?'Approved sample discoveries':'Suggested discoveries for review'}</h3><div class="sessionLine">Posture, Availability &amp; Tone <span class="badge lit">Practicing</span></div><div class="sessionLine">Permeability <span class="badge lit">Introduced</span></div><div class="sessionLine">Lateral <span class="badge lit">Practicing</span></div><p>These suggestions do not claim integration. In the connected version, Gab would review and correct them before the student sees an update.</p>${approved?'<p class="statusNote">Sample approved. Three discoveries and one practice task are now visible.</p><a class="primaryButton" href="#map">See the updated map →</a>':'<button class="primaryButton" id="approve">Approve sample discoveries</button>'}<p style="margin:18px 0 0;font-size:12px">Changes affect this demo tab only and reset on reload. No student record is written.</p></article>`;}
function view(){const v=location.hash.slice(1);return ['journey','map','practice','sessions'].includes(v)?v:'map';}
function render(){document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view())a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});({journey,map,practice,sessions}[view()])();}
content.addEventListener('click',e=>{
 const node=e.target.closest('[data-node]');if(node){selected=node.dataset.node;if(view()!=='map'){location.hash='map';setTimeout(()=>document.getElementById('detail')?.focus(),0);}else{renderGroups();renderDetail();document.getElementById('detail').focus();}return;}
 const filter=e.target.closest('[data-region]');if(filter){region=filter.dataset.region;document.querySelectorAll('[data-region]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.region===region)));renderGroups();return;}
 if(e.target.closest('#approve')){approved=true;Object.assign(progress,{'organization-1':'Practicing','connection-1':'Introduced','patterns-5':'Practicing'});selected='organization-1';sessions();announcement.textContent='Sample approved. Three discoveries added to the map.';}
});
document.getElementById('reset').addEventListener('click',()=>{approved=false;progress={'organization-0':'Introduced','steps-1':'Practicing'};selected='organization-0';region='All';search='';render();announcement.textContent='Sample journey reset. No real student data was changed.';});
window.addEventListener('hashchange',()=>{render();document.getElementById('main').focus();});render();
})();
