(() => {
'use strict';
const groups=window.ZOUK_ATLAS,details=window.ZOUK_DETAILS;
const nodes=groups.flatMap(g=>g.topics.map((name,i)=>({id:g.id+'-'+i,name,group:g})));
let crewAccount=null,accountState={mode:'loading'};
let progress={},approved=false,selected=null,landmark=null,preview=false,zoom=.72;
const WORLD=2600,ORIGIN=WORLD/2;
const point=(angle,radius)=>({x:ORIGIN+Math.cos(angle)*radius,y:ORIGIN+Math.sin(angle)*radius});
const universe=window.ATLAS_UNIVERSE,positions=universe.positions;
groups.forEach(g=>{g.gateway=universe.gateways.get(g.id);});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=id=>crewAccount?'Crew access':progress[id]||'Unexplored';
const content=document.getElementById('content');
const announcement=document.getElementById('announcement');
function nodeLink(id,label){return `<button class="topic ${progress[id]?'discovered':''}" data-node="${id}" aria-pressed="${id===selected}">${esc(label)}</button>`;}
function title(kicker,name,body){return `<div class="topline"><div><p class="eyebrow">${kicker}</p><h1>${name}</h1><p>${body}</p></div><div class="count"><b>${crewAccount?nodes.length:Object.keys(progress).length} / ${nodes.length}</b>${crewAccount?'concepts available<br>crew access':accountState.mode==='ready'?'concepts explored<br>saved lessons':'concepts explored<br>sample journey'}</div></div>`;}
function map(){
 content.innerHTML=title('02 / EXPLORE','Your journey starts here.','A living atlas of movement. Follow the light from your ship into distant clusters, planetary systems, and new questions.')+`<div class="flightToolbar"><div class="flightControls" role="group" aria-label="Map controls"><button id="zoomOut" aria-label="Zoom out">−</button><output id="zoomLevel" aria-live="polite"></output><button id="zoomIn" aria-label="Zoom in">+</button><button id="homeShip">Return to ship</button><button id="fitGalaxy">Whole galaxy</button><button data-landmark="horizon">Visit black hole</button><button data-landmark="observatory">Observatory</button></div><button id="previewToggle" ${accountState.mode==='ready'&&accountState.viewer.role!=='coach'?'hidden':''} class="filter" aria-pressed="${preview}" ${crewAccount?'disabled':''}>${crewAccount?'Full map · crew access':'Preview full curriculum'}</button></div><div class="mapFinder"><label for="conceptSearch">Find a concept</label><input id="conceptSearch" type="search" placeholder="Search your available concepts" autocomplete="off" aria-describedby="conceptSearchHint"><p id="conceptSearchHint">Search by name or constellation. Your saved discoveries stay unchanged.</p><p id="conceptSearchCount" role="status" aria-live="polite"></p><div id="conceptSearchResults" class="conceptSearchResults"></div></div><div class="discoveryBar"><label for="discoverySelect">Jump to a concept</label><select id="discoverySelect"><option value="">Your ship · center</option>${nodes.filter(n=>preview||progress[n.id]).map(n=>`<option value="${n.id}" ${n.id===selected?'selected':''}>${esc(n.name)} — ${status(n.id)}</option>`).join('')}</select><a href="#sessions">${accountState.mode==='ready'?'Open saved lessons':'Review sample lesson'} →</a></div><div class="mapLayout"><div class="galaxyFrame"><div id="flightViewport" class="flightViewport" tabindex="0" role="region" aria-label="Zouk galaxy. Drag or use arrow keys to pan. Use plus and minus to zoom, Home to return to ship."><div id="galaxySize"><div id="galaxy"></div></div></div><div class="flightCaption"><span id="mapMode">${crewAccount?'Crew access · full curriculum unlocked':preview?'Curriculum preview · all concepts visible':'Discovery mode · unexplored space is hidden'}</span><span>Drag to explore · + / − to zoom</span></div></div><aside id="detail" class="detail" aria-label="Selected concept" tabindex="-1"></aside></div><p class="mapFootnote">Stars, planets, and moons represent concepts—not levels of ability. Distances and constellation lines are a navigation metaphor, not prerequisites. Only saved lessons change your discoveries.</p>`;
 renderGroups();renderDetail();
 document.getElementById('conceptSearch').addEventListener('input',renderSearch);
 const viewport=document.getElementById('flightViewport');
 document.getElementById('zoomIn').onclick=()=>setZoom(zoom*1.25);
 document.getElementById('zoomOut').onclick=()=>setZoom(zoom/1.25);
 document.getElementById('homeShip').onclick=()=>{selected=null;landmark=null;renderGroups();renderDetail();setZoom(Math.max(zoom,.72));centerOn(ORIGIN,ORIGIN);};
 document.getElementById('fitGalaxy').onclick=()=>{setZoom(Math.min(viewport.clientWidth,viewport.clientHeight)/WORLD);centerOn(ORIGIN,ORIGIN);};
 document.getElementById('previewToggle').onclick=()=>{if(accountState.mode==='ready'&&accountState.viewer.role!=='coach')return;preview=!preview;map();announcement.textContent=preview?'Full draft curriculum visible. Student progress has not changed.':'Discovery view restored.';};
 document.getElementById('discoverySelect').onchange=e=>{selected=e.target.value||null;landmark=null;renderGroups();renderDetail();setZoom(Math.max(zoom,.9));const p=positions.get(selected)||{x:ORIGIN,y:ORIGIN};centerOn(p.x,p.y);if(selected)document.getElementById('detail').focus();};
 let drag=null;
 viewport.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0&&!e.target.closest('button')){drag={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging');e.preventDefault();}});
 viewport.addEventListener('pointermove',e=>{if(drag){viewport.scrollLeft=drag.left-(e.clientX-drag.x);viewport.scrollTop=drag.top-(e.clientY-drag.y);}});
 const stop=()=>{drag=null;viewport.classList.remove('dragging');};viewport.addEventListener('pointerup',stop);viewport.addEventListener('pointercancel',stop);viewport.addEventListener('lostpointercapture',stop);
 viewport.addEventListener('keydown',e=>{if(e.target!==viewport)return;const moves={ArrowLeft:[-90,0],ArrowRight:[90,0],ArrowUp:[0,-90],ArrowDown:[0,90]};if(moves[e.key]){e.preventDefault();viewport.scrollBy(...moves[e.key]);}else if(['+','=','-','Home'].includes(e.key)){e.preventDefault();if(e.key==='Home')centerOn(ORIGIN,ORIGIN);else setZoom(zoom*(e.key==='-'?.8:1.25));}});
 requestAnimationFrame(()=>{applyZoom();const p=positions.get(selected)||{x:ORIGIN,y:ORIGIN};centerOn(p.x,p.y);});
}
function renderSearch(){
 const query=document.getElementById('conceptSearch').value.trim();
 const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const matches=query?nodes.filter(n=>(preview||progress[n.id])&&normalize(n.name+' '+n.group.name).includes(normalize(query))):[];
 document.getElementById('conceptSearchCount').textContent=query?(matches.length?matches.length+' matching concept'+(matches.length===1?'':'s')+'.':'No match in your available concepts. Try another word or check your saved lessons.'):'';
 document.getElementById('conceptSearchResults').innerHTML=matches.map(n=>'<button type="button" class="searchConcept" data-node="'+n.id+'"><strong>'+esc(n.name)+'</strong><span>'+esc(n.group.name)+' · '+status(n.id)+'</span></button>').join('');
}
function applyZoom(){document.getElementById('galaxySize').style.width=WORLD*zoom+'px';document.getElementById('galaxySize').style.height=WORLD*zoom+'px';document.getElementById('galaxy').style.transform=`scale(${zoom})`;document.getElementById('zoomLevel').textContent=Math.round(zoom*100)+'%';}
function centerOn(x,y){const v=document.getElementById('flightViewport');v.scrollLeft=x*zoom-v.clientWidth/2;v.scrollTop=y*zoom-v.clientHeight/2;}
function setZoom(next){const v=document.getElementById('flightViewport'),x=(v.scrollLeft+v.clientWidth/2)/zoom,y=(v.scrollTop+v.clientHeight/2)/zoom;zoom=Math.max(.1,Math.min(1.6,next));applyZoom();centerOn(x,y);}
function renderGroups(){
 const visible=nodes.filter(n=>preview||progress[n.id]);
 const routes=nodes.filter(n=>progress[n.id]).map(n=>{const p=positions.get(n.id),g=n.group.gateway;return {d:`M ${ORIGIN} ${ORIGIN} Q ${g.x} ${g.y} ${p.x} ${p.y}`,color:n.group.color};});
 const paths=nodes.map(n=>{const i=Number(n.id.split('-').pop()),from=universe.parent(n.group,i),to=positions.get(n.id),lit=preview||progress[n.id];return `<path d="M ${from.x} ${from.y} L ${to.x} ${to.y}" stroke="${n.group.color}" opacity="${lit?.38:.07}"/>`;}).join('');
 const fog=preview?'':`<svg class="fogLayer" viewBox="0 0 ${WORLD} ${WORLD}" aria-hidden="true"><defs><radialGradient id="clearSpace"><stop offset="0" stop-color="black"/><stop offset=".6" stop-color="black"/><stop offset="1" stop-color="white"/></radialGradient><filter id="softRoute"><feGaussianBlur stdDeviation="28"/></filter><mask id="fogMask"><rect width="${WORLD}" height="${WORLD}" fill="white"/><circle cx="${ORIGIN}" cy="${ORIGIN}" r="390" fill="url(#clearSpace)"/>${visible.map(n=>{const p=positions.get(n.id);return `<circle cx="${p.x}" cy="${p.y}" r="210" fill="url(#clearSpace)"/>`;}).join('')}${routes.map(r=>`<path d="${r.d}" fill="none" stroke="black" stroke-width="110" filter="url(#softRoute)"/>`).join('')}</mask></defs><rect width="${WORLD}" height="${WORLD}" fill="#030610" fill-opacity=".82" mask="url(#fogMask)"/></svg>`;
 document.getElementById('galaxy').innerHTML=universe.background()+`<svg class="spaceLines" viewBox="0 0 ${WORLD} ${WORLD}" aria-hidden="true"><g fill="none" stroke-width="1.5">${paths}${routes.map(r=>`<path d="${r.d}" stroke="${r.color}" opacity=".22" stroke-dasharray="3 12"/>`).join('')}</g></svg>${groups.map(g=>{const active=preview||nodes.some(n=>n.group===g&&progress[n.id]);return `<div class="sectorName ${active?'charted':''}" style="left:${g.gateway.x}px;top:${g.gateway.y}px;--sector:${g.color}"><span>✧</span>${active?g.name:'Uncharted signal'}</div>`;}).join('')}${fog}${universe.landmarkMarkup()}${visible.map(n=>{const p=positions.get(n.id),kind=universe.type(n.id);return `<button class="galaxyNode ${kind} ${progress[n.id]||crewAccount?'discovered':'unknown'}" data-node="${n.id}" style="left:${p.x}px;top:${p.y}px;--sector:${n.group.color}" aria-label="${esc(n.name)} — ${status(n.id)}" aria-pressed="${n.id===selected}"><span class="nodeOrb" aria-hidden="true">${kind==='stellar'?'✦':''}</span><span class="nodeName">${esc(n.name)}</span>${progress[n.id]?'<span class="discoveryDot" aria-hidden="true"></span>':''}</button>`;}).join('')}<button id="ship" class="ship" style="left:${ORIGIN}px;top:${ORIGIN}px" aria-label="Your spaceship, journey origin"><span class="shipOrbit"></span>${window.GAB_CREW.saucer}<strong>YOUR SHIP</strong><small>Point of departure</small></button>`;
 document.getElementById('ship').onclick=()=>{selected=null;landmark=null;renderGroups();renderDetail();setZoom(Math.max(zoom,.72));centerOn(ORIGIN,ORIGIN);};
}
function renderDetail(){
 if(landmark){const l=universe.landmarks.find(x=>x.id===landmark);document.getElementById('detail').innerHTML='<p class="eyebrow">COSMIC LANDMARK · NOT A SKILL</p><h2>'+esc(l.title)+'</h2><p>'+esc(l.text)+'</p><a class="primaryButton" href="'+l.link+'">'+esc(l.cta)+' →</a>';return;}

 if(accountState.mode==='ready'&&!crewAccount&&!selected){document.getElementById('detail').innerHTML='<p class="eyebrow">YOUR SAVED MAP</p><h2>'+ (Object.keys(progress).length?'Your discoveries are here.':'Ready for your first discovery.')+'</h2><p>Concepts appear as your coach records what you explored together. Your latest recorded lesson sets each concept’s current status.</p><p>An empty map means lessons have not been recorded yet. It is not a measure of your ability, and you do not need to start your training over.</p><a class="primaryButton" href="#sessions">Open saved lessons →</a>';return;}

 if(!selected&&crewAccount){document.getElementById('detail').innerHTML='<p class="eyebrow">COMMAND DECK</p><span class="badge lit">Crew access</span><h2>Your whole galaxy is open.</h2><p>Explore every constellation and select any concept. Full access does not mark student skills as mastered.</p><a class="primaryButton" href="/mentorship-hub/">Open coaching dashboard →</a>';return;}
 if(!selected){document.getElementById('detail').innerHTML=`<p class="eyebrow">MISSION CONTROL</p><span class="badge lit">At your ship</span><h2>${approved?'Your first discoveries.':'A universe to discover.'}</h2><p>${approved?'Your sample lesson has revealed three concepts across the galaxy. Select a glowing star to explore what it means.':'You begin at the center with no concepts discovered. The surrounding space opens as reviewed lessons introduce new ideas.'}</p><section><h4>How the frontier expands</h4><p>A lesson reveals the concepts you explored with Gab. Familiar ideas stay lit while new branches emerge further out.</p><a class="primaryButton" href="#sessions">${approved?'View reviewed sample':'Try the sample lesson'} →</a></section><section><h4>Explore the draft</h4><p>Use “Preview full curriculum” to see the proposed branches without changing any progress.</p></section>`;return;}
 const n=nodes.find(n=>n.id===selected),d=details[n.id];
 if(accountState.mode==='ready'){document.getElementById('detail').innerHTML='<p class="eyebrow">'+esc(n.group.name)+'</p><span class="badge">'+status(n.id)+'</span><h2>'+esc(n.name)+'</h2><p>'+esc(d?.understand||'Named in Gab’s draft curriculum. The individual explanation is still in development.')+'</p><section><h4>What to notice</h4><p>'+esc(d.notice)+'</p></section><p class="guideLabel">Study guide · adapted from Gab’s curriculum draft. Your lesson establishes the specific version.</p>'+window.ATLAS_LIVE.detail(n.id,accountState);return;}
 const inLesson=['organization-1','connection-1','patterns-5'].includes(n.id)&&approved;
 const related=nodes.filter(x=>x.group===n.group&&x.id!==n.id).slice(0,3);
 document.getElementById('detail').innerHTML=`<p class="eyebrow">${n.group.name}</p><span class="badge ${progress[n.id]?'lit':''}">${status(n.id)}</span><h2>${esc(n.name)}</h2><p>${d?.understand?esc(d.understand):'Named in Gab’s draft curriculum. The individual lesson explanation is still to be developed.'}</p>${d?.notice?`<section><h4>What to notice</h4><p>${esc(d.notice)}</p></section>`:''}<section><h4>My practice</h4><p>${inLesson?'Sample task: explore the lateral with adjustable tone. Notice whether a change of direction requires a reset. This proposed exercise is for demonstrating the prototype.':'No personal exercise assigned in this sample. A reviewed lesson can connect this concept to your practice.'}</p>${inLesson?'<a class="secondaryButton" href="#practice">Open sample practice →</a>':''}</section><section><h4>My journey</h4><p>${inLesson?'Introduced or practiced in Sample private 01. Added after the demo review.':progress[n.id]?'Illustrative starting progress. This is not a record of a real lesson.':'Not yet explored in this sample. You can still read the concept.'}</p></section>${related.length?`<section><h4>In this constellation</h4><div class="topicList">${related.map(x=>nodeLink(x.id,x.name)).join('')}</div></section>`:''}${n.group.principle?`<details><summary>Go deeper · Gab’s draft</summary><p>${esc(n.group.principle)}</p><p>Constellation-level principle, not a complete definition of every concept here.</p></details>`:''}`;
}
function journey(){content.innerHTML=title('01 / YOUR DIRECTION','My journey','One place to find your focus, your latest discoveries and your next step.')+`<div class="box focusBox wide"><p class="sampleLabel">Sample student journey</p><h2>${approved?'From adjustable tone to an adaptable lateral.':'Begin with availability.'}</h2><p>${approved?'Your reviewed sample lesson connects body organization, permeability and a movement pattern.':'This sample starts at your ship with no discoveries. Review the example private lesson to reveal your first three concepts.'}</p><a class="primaryButton" href="${approved?'#practice':'#sessions'}">${approved?'Open my practice':'Review the sample lesson'} →</a></div><div class="cards wide"><section class="box"><h3>Your discoveries</h3><p>${Object.keys(progress).length} concepts explored. No percentage of mastery: discovery and integration are different steps.</p><a class="secondaryButton" href="#map">Explore my map →</a></section><section class="box"><h3>A connected learning loop</h3><p>Lesson → reviewed discoveries → focused practice → feedback in the next lesson.</p><p>Your map can grow while familiar concepts remain part of your practice.</p></section></div>`;}
function practice(){content.innerHTML=title('03 / BETWEEN LESSONS','My practice','A focused task connected to the concepts you are exploring.')+(approved?`<article class="box wide"><p class="sampleLabel">Illustrative exercise · Sample private 01</p><h2>Availability in the lateral</h2><p>Explore the lateral with adjustable tone. Notice whether a change of direction requires a reset.</p><ul><li>What changes when you use less unnecessary effort?</li><li>What helps information travel through the connection?</li><li>What would you like Gab to observe next time?</li></ul><p>This exercise demonstrates the experience; it is not a real assignment or a completed assessment.</p><div class="topicList">${['organization-1','connection-1','patterns-5'].map(id=>nodeLink(id,nodes.find(n=>n.id===id).name)).join('')}</div></article>`:`<div class="box wide"><h2>No sample assignment yet.</h2><p>Open Sessions and review the example lesson. Its exercise and related concepts will appear here after approval.</p><a class="primaryButton" href="#sessions">Open the sample lesson →</a></div>`);}
function sessions(){content.innerHTML=title('04 / LESSON HISTORY','My sessions','See what was explored, what was reviewed and what to practice next.')+`<article class="box wide"><p class="sampleLabel">Demo coach review · Not a Granola import</p><h2>Sample private 01</h2><div class="sessionNote"><p>“We explored adjustable tone, introduced permeability and practiced the lateral. The focus was changing direction without a preparatory reset.”</p><small>Invented lesson summary to demonstrate the workflow.</small></div><h3>${approved?'Approved sample discoveries':'Suggested discoveries for review'}</h3><div class="sessionLine">Posture, Availability &amp; Tone <span class="badge lit">Practicing</span></div><div class="sessionLine">Permeability <span class="badge lit">Introduced</span></div><div class="sessionLine">Lateral <span class="badge lit">Practicing</span></div><p>These suggestions do not claim integration. In your personal account, Gab or Steph reviews lesson notes before they update your map.</p>${approved?'<p class="statusNote">Sample approved. Three discoveries and one practice task are now visible.</p><a class="primaryButton" href="#map">See the updated map →</a>':'<button class="primaryButton" id="approve">Approve sample discoveries</button>'}<p style="margin:18px 0 0;font-size:12px">Changes affect this demo tab only and reset on reload. No student record is written.</p></article>`;}
function crew(){content.innerHTML=title('05 / FLIGHT CREW','Welcome aboard.','Meet the people guiding the mentorship ship.')+`<div class="crewFlightDeck">${window.GAB_CREW.saucer}<div><p class="sampleLabel">THE MENTORSHIP SAUCER</p><h2>Room for your next discovery.</h2><p>Captain Gab. Co-Captain Steph. A galaxy of movement to explore together.</p></div></div>${window.GAB_CREW.markup}<div class="box wide"><h3>${crewAccount?'Your command deck':'Your personal voyage'}</h3><p>${crewAccount?'Your coach account has access to the complete curriculum. Your existing coaching tools and student management remain in the member hub.':'Your own discoveries will shape your route. Sign in to see discoveries recorded by your coach.'}</p><a class="primaryButton" href="${crewAccount?'/mentorship-hub/':'#map'}">${crewAccount?'Open coaching dashboard':'Return to your ship'} →</a></div>`;}
function view(){const v=location.hash.slice(1);return ['journey','map','practice','sessions','crew','imports'].includes(v)?v:'map';}
function render(){
 if(accountState.mode==='loading'||accountState.mode==='error'){
 content.innerHTML='<div class="box wide"><h1>'+(accountState.mode==='loading'?'Opening your map…':'Your map is temporarily unavailable.')+'</h1><p>'+esc(accountState.message||'Checking your account and saved discoveries.')+'</p>'+(accountState.mode==='error'?'<button id="retryAtlas" class="primaryButton">Retry</button> <a class="secondaryButton" href="/mentorship-hub/">Member login</a>':'')+'</div>';
 document.getElementById('retryAtlas')?.addEventListener('click',()=>window.ATLAS_API.refresh());return;}
 if(view()==='imports'){
 document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view==='imports')a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(accountState.mode==='ready'){content.innerHTML=window.ATLAS_IMPORTS.markup(accountState);window.ATLAS_IMPORTS.bind(accountState);}
 else content.innerHTML='<div class="box"><h1>Coach sign-in required</h1><a class="primaryButton" href="/mentorship-hub/">Member login</a></div>';
 return;}
 if(accountState.mode==='ready'&&['journey','practice','sessions'].includes(view())){
 document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view())a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 content.innerHTML=window.ATLAS_LIVE.markup(view(),accountState);window.ATLAS_LIVE.bind(accountState);return;}
 document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view())a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});({journey,map,practice,sessions,crew}[view()])();}
content.addEventListener('click',e=>{
 const destination=e.target.closest('[data-landmark]');if(destination){const l=universe.landmarks.find(x=>x.id===destination.dataset.landmark);if(!l)return;landmark=l.id;selected=null;renderGroups();renderDetail();setZoom(Math.max(zoom,.72));centerOn(l.x,l.y);document.getElementById('detail').focus();return;}

 const node=e.target.closest('[data-node]');if(node){const id=node.dataset.node;if(!nodes.some(n=>n.id===id)||(accountState.mode==='ready'&&!preview&&!progress[id]))return;landmark=null;selected=id;zoom=Math.max(zoom,.9);if(view()!=='map'){location.hash='map';setTimeout(()=>document.getElementById('detail')?.focus(),0);}else{renderGroups();renderDetail();applyZoom();document.getElementById('discoverySelect').value=selected;const p=positions.get(selected);centerOn(p.x,p.y);document.getElementById('detail').focus();}return;}
 if(accountState.mode==='guest'&&e.target.closest('#approve')){approved=true;Object.assign(progress,{'organization-1':'Practicing','connection-1':'Introduced','patterns-5':'Practicing'});selected='organization-1';sessions();announcement.textContent='Sample approved. Three discoveries added to the map.';}
});
document.getElementById('reset').addEventListener('click',()=>{if(accountState.mode!=='guest')return;approved=false;progress={};selected=null;landmark=null;preview=!!crewAccount;zoom=.72;render();announcement.textContent='Sample journey reset. No real student data was changed.';});
window.addEventListener('atlas-state',e=>{
 accountState=e.detail;approved=false;selected=null;landmark=null;progress={};crewAccount=null;preview=false;
 document.getElementById('reset').hidden=accountState.mode!=='guest';
 document.getElementById('atlasImportsLink').hidden=accountState.mode!=='ready'||accountState.viewer.role!=='coach';
 const bar=document.getElementById('atlasAccount'),label=document.getElementById('atlasModeLabel');
 if(accountState.mode==='ready'){
   progress=window.ATLAS_LIVE.progress(accountState);
   if(accountState.fullAccess){crewAccount={title:window.GAB_CREW.titleFor(accountState.viewer),name:accountState.viewer.display_name};preview=true;}
   label.textContent='Saved member progress';
   bar.innerHTML='<span>'+esc(accountState.student.display_name)+' · '+(accountState.fullAccess?'Full curriculum access':'Saved discoveries')+'</span>'+(accountState.viewer.role==='coach'?'<label>Viewing<select id="atlasStudentSelect">'+accountState.students.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===accountState.student.id?'selected':'')+'>'+esc(p.display_name)+(p.id===accountState.viewer.id?' · My map':'')+'</option>').join('')+'</select></label>':'')+(accountState.viewer.role==='coach'?'<a href="#imports">Review inbox ('+(accountState.imports||[]).length+')</a>':'')+'<a href="/mentorship-hub/">Member hub →</a><button id="refreshAtlas" class="secondaryButton">Refresh saved map</button>';
   document.getElementById('atlasStudentSelect')?.addEventListener('change',e=>window.ATLAS_API.selectStudent(e.target.value));
   document.getElementById('refreshAtlas').addEventListener('click',()=>window.ATLAS_API.refresh());
 }else if(accountState.mode==='guest'){
   label.textContent='PUBLIC DEMO · NOT YOUR PERSONAL MAP';
   bar.innerHTML='<div><strong>You’re viewing an example journey.</strong><p>Sample discoveries are fictional and reset when this page reloads. Already a student? Sign in to see your own lessons and progress.</p></div><a class="primaryButton" href="/mentorship-hub/">Sign in to my student space →</a>';
 }else{label.textContent=accountState.mode==='error'?'Connection unavailable':'Connecting your map';bar.textContent='';}
 render();
});
window.addEventListener('hashchange',()=>{render();document.getElementById('main').focus();});render();
})();
