const fs=require('fs'),vm=require('vm'),assert=require('assert');
const listeners={};
const button={dataset:{reviewImport:'draft'},addEventListener(t,fn){listeners.review=fn;}};
const ctx={location:{hash:'#imports'},HashChangeEvent:class{},window:{dispatchEvent(){}},document:{querySelectorAll:s=>s==='[data-review-import]'?[button]:[],getElementById:()=>null}};
vm.createContext(ctx);
for(const file of ['zouk-map-data.js','atlas-live.js','atlas-imports.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const student={id:'student',display_name:'Student',role:'mentee'},coach={id:'coach',role:'coach'};
const draft={id:'draft',student_id:'student',lesson_date:'2026-08-27',source_title:'Source <script>',source_excerpt:'PRIVATE EXCERPT',mapping_notes:'UNCONFIRMED MAPPING',summary:'Proposed summary',practice:'Proposed exercise',concepts:{'organization-1':'Practicing'}};
const s={viewer:coach,students:[student,coach],student:coach,imports:[draft]};
assert(ctx.window.ATLAS_IMPORTS.markup(s).includes('1 drafts'));
ctx.window.ATLAS_IMPORTS.bind(s);listeners.review();
const review=ctx.window.ATLAS_IMPORTS.markup(s);
assert(review.includes('PRIVATE EXCERPT'));assert(review.includes('UNCONFIRMED MAPPING'));assert(!review.includes('Source <script>'));
assert.equal((review.match(/data-concept=/g)||[]).length,56);
const studentView=ctx.window.ATLAS_IMPORTS.markup({...s,viewer:student});
assert(!studentView.includes('PRIVATE EXCERPT'));assert(studentView.includes('Coach access required'));
ctx.location.hash='#sessions';assert.equal(ctx.window.ATLAS_IMPORTS.selected(s),null);
ctx.location.hash='#imports';
assert(ctx.window.ATLAS_IMPORTS.markup({...s,imports:[]}).includes('all caught up'));
console.log('PASS: coach review inbox, source escaping, editable full curriculum, student source isolation, manual sessions cannot accidentally approve a draft, processed draft leaves inbox.');
