// Dependency-free finalization. Run after branding and the isolated app copy.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=process.cwd(),out=path.join(root,'public');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const digest=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,12);
const htmlFiles=walk(out).filter(f=>f.endsWith('.html'));
const repeated=new Map();
for(const file of htmlFiles)for(const [,css]of fs.readFileSync(file,'utf8').matchAll(/<style>([\s\S]*?)<\/style>/g)){if(css.trim())repeated.set(css,(repeated.get(css)||0)+1);}
const unsafeExternalCss=css=>/@import\b|url\s*\(/i.test(css);
let externalizedBytes=0,versioned=0;const externalCssFiles=new Set(),errors=[];
for(const file of htmlFiles){let html=fs.readFileSync(file,'utf8');
 if(path.basename(file)==='mentorship.html'){
  html=html.replace('Long-term Brazilian Zouk and Lambada mentorship in New York City with Gab Lacarriere. Structured private training, kinesthetic practice, partner fundamentals, practica, goals, deliberate practice and a private learning portal.','Personalized Brazilian Zouk and Lambada mentorship in New York City with Gab Lacarriere. Identify what is holding you back, get a clear training direction and build practice that transfers into your dancing.');
  html=html.replace('<h1>A clear direction for your dancing.</h1>','<h1>Know what to practice.<br>Understand how to improve.</h1>');
  html=html.replace('<p class="lede">Work on what matters to you with private coaching, guided practice and feedback. Build skills you can use with different partners and music, with a personal training space to support practice between sessions.</p>','<p class="lede">A personalized Brazilian Zouk and Lambada mentorship for dancers who want stronger foundations, clearer direction and lasting progress. We identify what is holding you back, choose what matters most now, and turn coaching into practice you can actually use on the dance floor.</p>');
  html=html.replace('<div class="actions"><a class="btn" href="#apply">Apply to Mentorship</a><a class="btn ghost" href="#your-learning-worlds">See Zoukable + Atlas</a>','<div class="actions"><a class="btn" href="#apply">Apply for mentorship</a><a class="btn ghost" href="#membership">See what is included</a><a class="btn ghost" href="#your-learning-worlds">See Zoukable + Atlas</a>');
  html=html.replace('<div class="card space"><h3>Find your focus</h3><p>Identify what is holding you back and choose a clear priority for your practice.</p></div>','<div class="card space"><h3>Know what to work on</h3><p>Identify the patterns, skills or habits that are limiting your dancing and choose a clear priority instead of trying to improve everything at once.</p></div>');
  html=html.replace('<div class="card space"><h3>Make progress between sessions</h3><p>Practice with a purpose, revisit what you learn and explore it with different partners and music.</p></div>','<div class="card space"><h3>Turn coaching into practice</h3><p>Leave each coaching cycle with concrete work to revisit between sessions, then bring what you discover back into your dancing.</p></div>');
  html=html.replace('<div class="card space"><div class="price">$200 / month</div><p>Each month: 1 hour of private coaching, a 30-minute Kinesthetic Practice Session, 4 group classes and access to Zoukable, your personal Zouk Atlas and the mentorship member hub.</p></div>','<div class="card space"><div class="price">$200 / month</div><p>Ongoing mentorship with monthly private coaching, Kinesthetic Practice, group training, practica, and access to Zoukable, your personal Zouk Atlas and the mentorship member hub.</p></div>');
  const why=`\n<section class="sec soft" id="why-mentorship"><div class="w"><div class="kicker">Why mentorship</div><h2>More classes are not always the missing piece.</h2><p class="lede">When you already train but are unsure what deserves your attention, mentorship gives your practice a direction. The goal is not to collect more material. It is to understand your dancing well enough to know what to work on next.</p><div class="grid" style="margin-top:28px"><div class="card"><h3>Diagnose</h3><p>Notice recurring limitations in technique, timing, connection, movement quality or decision-making.</p></div><div class="card"><h3>Prioritize</h3><p>Choose a small number of useful priorities so your practice has a purpose instead of becoming a list of disconnected exercises.</p></div><div class="card"><h3>Integrate</h3><p>Revisit the work through individual coaching, guided practice, group training and real social dancing, then adjust the plan as your needs change.</p></div></div></div></section>\n`;
  html=html.replace('\n<section class="sec soft"><div class="w g2">',why+'\n<section class="sec" id="membership"><div class="w g2">');
  html=html.replace('<div class="kicker">What is included</div>\n    <h2>Your $200 monthly membership.</h2>','<div class="kicker">What is included</div>\n    <h2>A full month of guided training for $200.</h2>');
  html=html.replace('<li><strong>4 group classes each month</strong><br>Held on the second and fourth Sundays, 1–3 PM, New York time.</li>','<li><strong>Group training + practica</strong><br>Regular mentorship group work, partner practice and guided integration.</li>');
  html=html.replace('<p class="muted">See your current training priorities, find your assigned practice, revisit earlier material and share feedback with Gab. Your progress and resources stay together in your member space.</p>','<p class="muted">See your current training priorities, find your assigned practice and revisit earlier material. Your progress and resources stay together in your member space.</p>');
  html=html.replace('<div class="mini"><span>Training goals</span><span>Practice assignments</span><span>Review reminders</span><span>Coach feedback</span><span>Progress history</span></div>','<div class="mini"><span>Training goals</span><span>Practice assignments</span><span>Review reminders</span><span>Session discoveries</span><span>Progress history</span></div>');
  const membershipRules=`\n<div class="card" style="margin-top:24px;min-height:auto"><h3>How the monthly membership works</h3><p><strong>Capacity:</strong> the mentorship is limited to 30 active members.</p><p><strong>Pause:</strong> you can ask to pause your subscription when you need time away. Because places are limited, availability when returning depends on current capacity.</p><p><strong>Monthly use:</strong> included sessions and group benefits are intended for the month in which they are offered. Unused sessions do not automatically accumulate or create future credit. Gab may make exceptions when appropriate.</p><p><strong>Refunds:</strong> there is no blanket no-refund rule. If something unusual happens, contact Gab and the situation can be handled individually, subject to applicable law.</p></div>\n`;
  html=html.replace('    <p class="muted">Contact Gab for the Sunday venue and to arrange your private coaching and Kinesthetic Practice Session.</p>','    <p class="muted">Contact Gab for the current group schedule and to arrange your private coaching and Kinesthetic Practice Session.</p>'+membershipRules);
  const referral=`\n<section class="sec soft" id="referral-reward"><div class="w"><div class="kicker">Mentorship Referral Reward</div><h2>Help the community grow. Earn an extra Kinesthetic Practice class.</h2><p class="lede">If you refer a dancer who joins the Mentorship Program and completes three paid months, you receive one Kinesthetic Practice class free.</p><div class="grid" style="margin-top:28px"><div class="card"><h3>1. Refer</h3><p>Tell a dancer about the mentorship and ask them to mention your name when they join.</p></div><div class="card"><h3>2. They complete 3 paid months</h3><p>The referral qualifies after their third paid month is completed.</p></div><div class="card"><h3>3. Your reward</h3><p>You earn one free Kinesthetic Practice class. Each qualifying referral earns one reward.</p></div></div></div></section>\n`;
  html=html.replace('\n<section id="your-learning-worlds"',referral+'\n<section id="your-learning-worlds"');
  html=html.replace('<div class="kicker">Before you join</div><h2>Start with a conversation.</h2>','<div class="kicker">Before you join</div><h2>You do not need to know exactly what is wrong with your dancing.</h2><p class="lede">Start by telling Gab what you want to feel more capable of doing. The first conversation is there to clarify the problem together and decide whether ongoing mentorship is the right format.</p>');
 }
 if(path.basename(file)==='mentorship-hub.html'){
  const memberReferral=`<section class="sec soft" id="member-referral"><div class="w"><div class="kicker">Member benefit</div><h2>Mentorship Referral Reward</h2><div class="card" style="min-height:auto"><h3>Refer a dancer → earn a Kinesthetic Practice class</h3><p>If someone you refer joins the Mentorship Program and completes three paid months, you receive one Kinesthetic Practice class free.</p><p class="muted"><strong>How to make sure it counts:</strong> ask the new member to mention your name when they join. The reward is earned after their third paid month. Each qualifying referral earns one reward.</p><div class="actions"><a class="btn" href="https://wa.me/19295864994?text=Hi%20Gab%2C%20I%20referred%20someone%20to%20the%20mentorship%20program%3A%20" target="_blank" rel="noopener">Tell Gab about a referral</a></div></div></div></section>`;
  html=html.replace('</main>',memberReferral+'</main>');
 }
 html=html.replace(/<style>([\s\S]*?)<\/style>/g,(tag,css)=>{
  if(css.length<500||unsafeExternalCss(css))return tag;
  const kind=(repeated.get(css)||0)>=2?'shared':'page';
  const rel=`/generated/${kind}-${digest(css)}.css`,dest=path.join(out,rel);
  fs.mkdirSync(path.dirname(dest),{recursive:true});
  if(!fs.existsSync(dest))fs.writeFileSync(dest,css);
  externalizedBytes+=Buffer.byteLength(css);externalCssFiles.add(rel);
  return '<link rel="stylesheet" href="'+rel+'">';
 });
 html=html.replace(/\b(src|href)="([^"#]+)"/g,(tag,attr,url)=>{if(!/\.(css|js)(\?|$)/i.test(url)||/^(https?:|\/\/|data:)/.test(url))return tag;const [pathname]=url.split('?');const local=pathname.startsWith('/')?path.join(out,pathname):path.resolve(path.dirname(file),pathname);if(!local.startsWith(out+path.sep)||!fs.existsSync(local)){errors.push(path.relative(out,file)+': missing '+url);return tag;}versioned++;return attr+'="'+pathname+'?v='+digest(fs.readFileSync(local))+'"';});
 fs.writeFileSync(file,html);
}
for(const file of walk(out)){const rel=path.relative(out,file);if(/(^|\/)(database|design|tests|work|scripts|\.git)(\/|$)|\.(sql|cjs|md|py)$/.test(rel))errors.push('Non-public file: '+rel);}
if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(`Finalized ${htmlFiles.length} pages; ${versioned} asset references versioned from content; ${externalizedBytes} inline CSS bytes externalized to ${externalCssFiles.size} generated stylesheets.`);
