const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../zoukable/core.js');
const now=new Date('2026-09-11T12:00:00Z');
const drill={id:'a',version:1,title:'A',status:'published',role:'either',partner_mode:'solo',physical_load:'low',min_seconds:60,target_seconds:120};
const ctx={minutes:5,mode:'solo',role:'leader',side:'left',gentle:false};
test('no unsafe URL protocols',()=>{for(const s of ['javascript:alert(1)','data:text/html,x','http://example.com','oops'])assert.equal(C.safeURL(s),null);assert.equal(C.safeURL('https://example.com'),'https://example.com/');});
test('escapes user content',()=>assert.equal(C.esc('<img a="x">'), '&lt;img a=&quot;x&quot;&gt;'));
test('clearance is required even for experienced users',()=>{const d={...drill,requires_clearance:true};assert.equal(C.canPractice(d,ctx,[],'u'),false);assert.equal(C.canPractice(d,ctx,[{drill_id:'a',user_id:'u'}],'u'),true);assert.equal(C.canPractice(d,ctx,[{drill_id:'a',user_id:'other'}],'u'),false);});
test('role, partner and physical conditions filter drills',()=>{assert.equal(C.canPractice({...drill,role:'follower'},ctx),false);assert.equal(C.canPractice({...drill,partner_mode:'partner'},ctx),false);assert.equal(C.canPractice({...drill,physical_load:'high'},{...ctx,gentle:true}),false);});
test('respects time budget and minimum dose',()=>{const q=C.buildSession([drill,{...drill,id:'b'},{...drill,id:'c'}],[],ctx,[],'u');assert.equal(q.reduce((n,x)=>n+x.seconds,0),300);assert.deepEqual(q.map(q=>q.seconds),[120,120,60]);});
test('does not confuse left and right or roles',()=>{const d={...drill,side_specific:true};const st=[{drill_id:'a',drill_version:1,role:'leader',side:'right',partner_mode:'solo',due_at:'2026-01-01'}];assert.equal(C.buildSession([d],st,ctx,[],'u')[0].reason,'First practice');});
test('same-session repetition does not accelerate spacing',()=>{const s={step:3,due_at:new Date(+now-1000),last_reviewed_at:new Date(+now-2000)};assert.equal(C.nextReview(s,'easy',false,+now).step,3);});
test('delayed review can extend interval',()=>{const s={step:3,due_at:new Date(+now-1000),last_reviewed_at:new Date(+now-86400000)};assert.equal(C.nextReview(s,'good',false,+now).step,4);});
test('failure does not reset accumulated state',()=>assert.equal(C.nextReview({step:5},'failed',false,+now).step,4));
test('revealed instruction brings next review closer',()=>{const r=C.nextReview({step:5},'easy',true,+now);assert.equal(+new Date(r.due_at)-now,86400000);});
test('stopped attempts never award XP',()=>assert.equal(C.stats([{status:'stopped',practice_seconds:100}],now).xp,0));
test('equal practice XP for honest failure and success; daily drill cap',()=>{const logs=Array.from({length:5},(_,i)=>({status:'completed',completed_at:now,drill_id:'a',result:i%2?'failed':'easy',practice_seconds:60}));assert.equal(C.stats(logs,now).xp,30);});
test('tresillo is explicitly 3+3+2 over eight cells',()=>{const h=C.rhythmHits('tresillo');assert.deepEqual([h[1]-h[0],h[2]-h[1],8-h[2]+h[0]],[3,3,2]);});
test('does not guess ambiguous spoken rhythm counts',()=>{assert.equal(C.rhythmHits('contemporary-1'),null);assert.deepEqual(C.rhythmHits('contemporary-1',{'contemporary-1':[0,2,6]}),[0,2,6]);});
